### ISSUE TITLE
Firestore: allow field paths to start with a number

### ISSUE THREAD

**Issue by nilsegger** [googleapis/python-firestore#10]
So I just realized that if I have a document like:
```
{
   "0foo": "text",
   "bar": "text"
}

```
This will work:
`doc_ref.get()`

This will work:
`doc_ref.get(["bar"])`

And this will not because the field path begins with a number:
`doc_ref.get(["0foo"])`
... and resulting in a `google.api_core.exceptions.InvalidArgument: 400 Invalid property path "0foo"`.

What I dont understand is why I would even be allowed to create documents with these fields, and only first get an error trying to partially retrieve the documents. I feel like this should already give an error `doc_ref.set(set_dict)`.

I let the admin sdk generate the documents id with `ref.document()`, sometimes I will have a document with references to these, or even copies of the document, it is redundant but increases the speed when retrieving collections. In short these documents contains maps with other documents where the key (field path) will be the document id. This document sometimes has a starting number instead of character, which leads to my "bug".

An easy workaround to this will be to generate the documents id differently or check if they have a starting number.

**Comment by IlyaFaer** [comment]
@nilsegger, have you tried backticks into `get()`? I've created a doc (on Google Cloud Console) with a field, which name starting with digits. `get()` failed with `Invalid property path`:

![image](https://user-images.githubusercontent.com/26030071/74522817-01c48380-4f2d-11ea-803f-6a9cce109f34.png)


But after adding backticks it worked fine for me:

![image](https://user-images.githubusercontent.com/26030071/74522770-e5c0e200-4f2c-11ea-99e1-9b205a131be2.png)

**Comment by IlyaFaer** [comment]
@nilsegger, have you tried to add backticks into `get()`? I've created a doc (on Google Cloud Console) with a field, which name starting with digits. `get()` failed with `Invalid property path`:

![74522817-01c48380-4f2d-11ea-803f-6a9cce109f34](https://user-images.githubusercontent.com/26030071/74523099-8b745100-4f2d-11ea-97be-e77d86064275.png)


But after adding backticks it worked fine for me:

![2](https://user-images.githubusercontent.com/26030071/74523166-a646c580-4f2d-11ea-9192-65d8461d4999.png)

**Comment by BenWhitehead** [comment]
@crwilcox Thoughts here? My best guess is there is some odd behavior happening with the key being passed to the underlying dict.  The backend isn't erroring when creating the doc so it's being returned as part of a query/get.

**Comment by nilsegger** [comment]
@IlyaFaer 
Yes it seems to be working fine with backticks. Thanks a lot.

Short sidequestion, are these backticks made by firestore to escape strings or is this something python does which I did not know of?

**Comment by IlyaFaer** [comment]
@nilsegger, I believe it's from Firestore as this behavior is mentioned in [docs](https://firebase.google.com/docs/firestore/quotas) - see *Constraints on field paths*. I'd say it's formulated not very understandable (well, for me), but backticks tip is there, and suppose to be actual for any language

**Comment by crwilcox** [comment]
@BenWhitehead

**Comment by IlyaFaer** [comment]
@BenWhitehead, I assume this issue can be closed, as we figured out that this behavior described in docs.

_P.S. I thought about auto adding backticks into field name in case it starts with a digit, but I'm not sure if this is a good idea as docs already mentioned what to do in such a cases_

**Comment by BenWhitehead** [comment]
SGTM @IlyaFaer
