### ISSUE TITLE
export_documents return type changed between 1.7.0 and 1.8.1

### ISSUE THREAD

**Issue by therefromhere** [googleapis/python-firestore#100]
Hi, I'm using export_documents to backup Firestore, and I've found that the return type seems to have changed between 1.7.0 and 1.8.1.  Is this intentional?

With 1.7.0 it returns an with `metadata` and `name` properties (edit: I think this is an instance of `google.longrunning.operations_pb2.Operation`?).
With 1.8.1 it returns an instance of `google.api_core.operation.Operation` that has a property `operation`, with those properties - so it seems like the result from 1.7.0 is nested in the result from 1.8.1.

#### Environment details

  - OS type and version:

Ubuntu 20.04

  - Python version: `python --version`

3.7.7

  - pip version: `pip --version`

19.2.3

  - `google-cloud-firestore` version: `pip show google-cloud-firestore`

1.7.0 vs 1.8.1

#### Steps to reproduce

See example code below, this works with client package 1.7.0, but fails with 1.8.1

#### Code example

```python
import os

from google.cloud.firestore_admin_v1.gapic import firestore_admin_client
from google.api_core.operations_v1 import operations_client
from google.api_core import operation as core_operation
from google.cloud.firestore_admin_v1.proto import operation_pb2


project_id = os.environ["GOOGLE_CLOUD_PROJECT"]
output_bucket_name = os.environ["OUTPUT_BUCKET_NAME"]

client = firestore_admin_client.FirestoreAdminClient()
name = client.database_path(project_id, "(default)")
output_uri_prefix = f"gs://{output_bucket_name}"

print("start operation")

operation = client.export_documents(
  name=name,
  output_uri_prefix=output_uri_prefix,
)

print(f"operation is a {operation.__class__.__name__} = {operation}")

operation_client = operations_client.OperationsClient(
  client.transport.channel)

operation_future = core_operation.from_gapic(
      operation,
      operation_client,
      operation_pb2.ExportDocumentsResponse,
      metadata_type=operation_pb2.ExportDocumentsMetadata,
  )

print("await operation completion")

# Block until the operation has completed if it's not already done
operation_future.result()

print("done")
```

#### Stack trace

```
Traceback (most recent call last):
  File "/home/johnc/.config/JetBrains/PyCharm2020.1/scratches/scratch_23.py", line 32, in <module>
    metadata_type=operation_pb2.ExportDocumentsMetadata,
  File "/home/johnc/.cache/pypoetry/virtualenvs/gweb-digital-guru-aZuuZtrT-py3.7/lib/python3.7/site-packages/google/api_core/operation.py", line 325, in from_gapic
    refresh = functools.partial(operations_client.get_operation, operation.name)
AttributeError: 'Operation' object has no attribute 'name'
```

**Comment by therefromhere** [comment]
The fix to my code seems to be simple - just changing

```
operation_future = core_operation.from_gapic(
      operation,
      operation_client,
      operation_pb2.ExportDocumentsResponse,
      metadata_type=operation_pb2.ExportDocumentsMetadata,
  )
```

to

```
operation_future = core_operation.from_gapic(
      operation.operation,
      operation_client,
      operation_pb2.ExportDocumentsResponse,
      metadata_type=operation_pb2.ExportDocumentsMetadata,
  )
```

I just wanted to confirm this was intended :)

**Comment by therefromhere** [comment]
I think the change is it was previously returning a  `google.longrunning.operations_pb2.Operation` and is now returning a  `google.api_core.operation.Operation` (which has a property `operation` that's a `google.longrunning.operations_pb2.Operation`).

**Comment by crwilcox** [comment]
@busunkim96 I have to assume this came from the gen'd side. Is this a known issue or unique to firestore?

**Comment by busunkim96** [comment]
We haven't changed anything in the generator or api-core related to LROs. I'd suspect it's something from annotations trickling through?

The expectation is that LROs return `google.api_core.operation.Operation`

**Comment by therefromhere** [comment]
BTW, if it's relevant, I'm using `google-api-core==1.21.0`

**Comment by busunkim96** [comment]
Confirmed that the client returned `google.longrunning.operations_pb2.Operation` through 1.7.0.

1.7.0: https://github.com/googleapis/python-firestore/blob/777d0e3c5c466a3460d8f57e3680fddaa1675c03/google/cloud/firestore_admin_v1/gapic/firestore_admin_client.py#L648-L738

1.8.1: https://github.com/googleapis/python-firestore/blob/71737a60eab55d755d6f784d460bfa0b2c1215f5/google/cloud/firestore_admin_v1/gapic/firestore_admin_client.py#L885-L990

https://github.com/googleapis/googleapis/commit/2427a3a0f6f4222315362d973d91a082a3a884a7 added LRO-related annotations in December. My guess would be that this was either (1) improperly configured or (2) the generator was buggy and didn't recognize this method as an LRO.

The present state is the desired behavior, but this is technically a breaking a change. 😕

**Comment by therefromhere** [comment]
All good, thanks clarifying & for the quick response!
