### ISSUE TITLE
Separate constructor invalid path test cases

### ISSUE THREAD

**Issue by rafilong** [googleapis/python-firestore#102]
Current [constructor tests](https://github.com/googleapis/python-firestore/blob/master/tests/unit/v1/test_collection.py#L64-L72) test multiple failure conditions in one test case. By separating these tests into multiple test cases it will be more clear which failure is the cause.

```
def test_constructor_invalid_path(self):
    with self.assertRaises(ValueError):
        self._make_one()
    with self.assertRaises(ValueError):
        self._make_one(99, "doc", "bad-collection-id")
    with self.assertRaises(ValueError):
        self._make_one("bad-document-ID", None, "sub-collection")
    with self.assertRaises(ValueError):
        self._make_one("Just", "A-Document")
```

**Comment by rafilong** [comment]
@BenWhitehead on second thought, on failure the line of the assertion should indicate which part of the test failed. I agree that it will be more straightforward to diagnose if the test case was separated into multiple tests, but as consequence we are introducing a large number of test cases. Could that potentially be a problem?

For instance, if the constructor failed to raise an error in any case, we would be raising potentially more flags than necessary.

**Comment by BenWhitehead** [comment]
The thought I've got here is that the asseritions cause short-circuiting. So if the first scenario results in an assertion failure, the other 3 won't be ran, so we'll know that the first scenario fails but be inconclusive about the other three. If all 4 are individual tests, all 4 will be ran and evaluated on their own.

**Comment by rafilong** [comment]
Really good point, I hadn't considered that.
