### ISSUE TITLE
Fix type of `get_all` gRPC call

### ISSUE THREAD

**Issue by rafilong** [googleapis/python-firestore#125]
The type for the generated `batch_get_all` is `AsyncIterable[firestore.BatchGetDocumentsResponse]`, but was incorrectly mocked as `Iterable[firestore.BatchGetDocumentsResponse]`.

**Comment by crwilcox** [comment]
@rafilong can you open this against https://github.com/googleapis/gapic-generator-python as well?

**Comment by rafilong** [comment]
Sorry, I just realized my description was a bit misleading. The incorrectly mocked type was in the Firestore test I wrote to test `get_all`, in which I was mocking the return type of `batch_get_all`. The generated code functioned fine, my use of it was slightly flawed.
