### ISSUE TITLE
Firestore API docs do not reflect the released distributions

### ISSUE THREAD

**Issue by hiranya911** [googleapis/python-firestore#13]
API docs for Cloud Firestore seem to be auto-generated from the master branch: https://googleapis.github.io/google-cloud-python/latest/firestore/collection.html#google.cloud.firestore_v1beta1.collection.CollectionReference

This contains several APIs that are not yet available in any of the released distributions (e.g. `stream()`, `list_documents()`).  This often sends developers down the wrong path, that results in Python attribute errors.

**Comment by BenWhitehead** [comment]
With the new docs site https://googleapis.dev/python/firestore/latest/collection.html , the docs are versioned along with the release of google-firestore and can be switched between with the drop down in the lower-right corner.
