### ISSUE TITLE
Add autospec or manual spec to async unit testing

### ISSUE THREAD

**Issue by rafilong** [googleapis/python-firestore#133]
As we create our own `AsyncMock` class, extending `MagicMock`, we cannot use `create_autospec` to create mocks in async unit tests. We should investigate creating a `create_autospec` counterpart for async, or alternatively manually spec classes that are tested.

https://github.com/googleapis/python-firestore/pull/123#discussion_r459224691

**Comment by meredithslota** [comment]
Closing this out as a "Won't Fix".
