### ISSUE TITLE
Firestore document replaced when sending set(dict, merge=True)

### ISSUE THREAD

**Issue by thrykol** [googleapis/python-firestore#138]
#### Issue

If `set(dict, merge=True)` is called on a document with a single field whose value is set to `SERVER_TIMESTAMP`, the client is replacing all existing data in the document with the single field. `SERVER_TIMESTAMP` and merge are working properly when more than one field is being updated.

#### Similar issues

https://github.com/googleapis/google-cloud-python/issues/7215

https://github.com/googleapis/python-firestore/issues/14

#### Environment details

  - OS type and version: Linux
  - Python version: 3.7.8
  - pip version: 20.2
  - `google-cloud-firestore` version: 1.8.1

##### Full Google ecosystem dependency list

- cloudevents==0.3.0
- firebase-admin==4.3.0
- functions-framework==2.0.0
- gcloud==0.18.3
- google-api-core==1.22.0
- google-api-python-client==1.10.0
- google-auth==1.20.0
- google-auth-httplib2==0.0.4
- google-cloud-core==1.3.0
- google-cloud-firestore==1.8.1
- google-cloud-iot==1.0.0
- google-cloud-pubsub==1.7.0
- google-cloud-storage==1.30.0
- google-crc32c==0.1.0
- google-resumable-media==0.7.0
- googleapis-common-protos==1.52.0
- grpc-google-iam-v1==0.12.3

#### Steps to reproduce

1. Add a document to the collection with some fields added.
2. Add a new field with a timestamp value set to `SERVER_TIMESTAMP` using the `set(dict, merge=True)`

#### Code example

```python
from firebase_admin import firestore

client = firestore.client()
for _ in range(10):
    print('initializing document')
    client.collection('demo').document('00000000').set({
        u'my-field': {
            u'one': 1,
            u'two': 2,
        },
        u'other': True
    })  # (re)create the document
    time.sleep(2)

    print('merging document')
    client.collection('demo').document('00000000').set({
        u'timestamps': {
           u'widget': SERVER_TIMESTAMP,
        },
    }, merge=True)  # overrides the existing document with the single field `timestamps.widget`
    time.sleep(2)
```

**Comment by giano574** [comment]
I noticed the same behaviour. It also applies to nested fields:


```python
client.collection('demo').document('00000000').set({
    u'my-field': {
        u'one': 1,
        u'two': 2,
    }
})  # create the document
time.sleep(2)

print('merging document')
client.collection('demo').document('00000000').set({
    u'my-field': {
        u'three': SERVER_TIMESTAMP,
    },
}, merge=True)
time.sleep(2)
```

The resulting document looks as follows:
```json
{
  "my-field": {
    "three": <timestamp>
  }
}
```

**Comment by HemangChothani** [comment]
@giano574 @thrykol 
Here is the sample code for that:

```python
from google.cloud import firestore_v1 

client = firestore_v1.Client()
collection_name = "collection_name"
document_id = "your-document" + unique_resource_id("-")
document = client.document(collection_name, document_id)

data = {"foo": {"bar": "baz"}, "scoop": {"barn": 981}, "other": True}
write_result = document.create(data)

field_updates = {"foo.now": firestore_v1.SERVER_TIMESTAMP}
write_result = document.update(field_updates)

snapshot1 = document.get()
stored_data = snapshot1.to_dict()

print(stored_data)
```
Output:
```
{
    'other': True,
    'scoop': {
                  'barn': 981
     },
    'foo': {
                'now': DatetimeWithNanoseconds(2020, 9, 7, 7, 10, 57, 777000, tzinfo=<UTC>),
                'bar': 'baz'
    }
}
```

**Comment by HemangChothani** [comment]
Please follow-up / reopen if you can provide more information.
