### ISSUE TITLE
Improve type hints, add types to method params

### ISSUE THREAD

**Issue by crwilcox** [googleapis/python-firestore#140]
#134 adds type hints to the manual surface. That said, much of the merged types, maybe all, do not type params to functions. For instance:

```
    async def list_documents(
        self, page_size=None
    ) -> AsyncGenerator[AsyncDocumentReference, None]
```

`page_size` is an `int`. Adding these type hints would further assist users.

Work should target `v2-staging` branch for the time being.

**Comment by Yogendra0Sharma** [comment]
@crwilcox can i work on this issue?

**Comment by crwilcox** [comment]
@Yogendra0Sharma feel free to submit a PR!

**Comment by Yogendra0Sharma** [comment]
@crwilcox do we have to use type hint for all function parameters?

**Comment by crwilcox** [comment]
If you can contribute a portion that is fine. Do you have an idea of places you think more type hints would be helpful for your use?
