### ISSUE TITLE
firestore.Client(project=<project_name>) raises a very vague error if the project_name contains a space character.

### ISSUE THREAD

**Issue by samuelashraff** [googleapis/python-firestore#149]
When you initialize your firestore database like so `firebase.Client(project=...)` where the given project name has a space character in it, saving data to the database will cause it to crash raising quite a vague and unhelpful error: `google.api_core.exceptions.Unknown: None`. The error should be more descriptive.

**Comment by HemangChothani** [comment]
@samuelashraff  I have tried with the updated `google-cloud-firestore` but got a descriptive error like: `InvalidArgument: 400 Project id sample project is malformed: it either contains invalid characters or is too long. Look at https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects for instructions in how to get a project's id.
`


Here is the sample code:
```python
from google.cloud import firestore_v1
db = firestore_v1.Client(project='sample project')
# any database query
```

Environment details:

    google-cloud-firestore==1.8.1
    google-api-core==1.22.0
    google-auth==1.19.2
    google-cloud-core==1.4.1
 

If it's still reproducible then please provide more details.
