### ISSUE TITLE
Composite index creation url is not working

### ISSUE THREAD

**Issue by mikheillomidze** [googleapis/python-firestore#151]
Hello, 

I have multi field query with ordering: `collection.where("field", "==", "value").where("field2", "==", "value").order_by("field3", "DESCENDING")` 

I am getting error: `google.api_core.exceptions.FailedPrecondition: 400 The query requires an index. You can create it here: https://some.link/here`

When I click link, it does not open Composite index creation pop-up.

I was not able to create index on my own. 

Any advices?

**Comment by mikheillomidze** [comment]
I think, there is issue in link generation.

I copied query string, added it to the firebase console link and it worked.

This is what is in error : https://console.firebase.google.com/v1/r/project/your-project/firestore/indexes?create_composite=somestringhere
This is what it should be: https://console.firebase.google.com/project/your-project/firestore/indexes?create_composite=somestringhere

**Comment by HemangChothani** [comment]
@mikheillomidze  If you are using firestore then the link is working perfectly fine, make sure you have logged in with correct user and verify the selected project on console.

It will autometically redirect from ` https://console.firebase.google.com/v1/r/project` to ` https://console.firebase.google.com/project`

**Comment by tseaver** [comment]
@mikheillomidze Please feel follow up / reopen if @HemangChothani 's answer isn't sufficient.
