### ISSUE TITLE
FieldPath.document_id() can't be used in queries

### ISSUE THREAD

**Issue by marban** [googleapis/python-firestore#181]
It seems the static document_id() (which translates to "__name__") can't be used in queries. E.g.

`collection('abc').where(FieldPath.document_id(), "in", somelist).get()`

=> "google.api_core.exceptions.InvalidArgument: 400 __key__ filter value must be a Key"

**Comment by HemangChothani** [comment]
@marban Here is the sample:
```python
from google.cloud import firestore_v1
db = firestore_v1.Client()

doc_ref = db.collection('users-test').where(firestore_v1.field_path.FieldPath.document_id(), 'in', [db.document('users-test/a'), db.document('users-test/b')]).stream()
for doc in doc_ref:
    print(doc.to_dict())
