### ISSUE TITLE
typing changes block synth

### ISSUE THREAD

**Issue by tseaver** [googleapis/python-firestore#188]
PR #134 made manual changes to generated code in order to get `pytype` running / passing under CI.  Until we fix the generator / templates / bazel stuff, we cannot do generation without breaking `pytype` (synthtool would even remove it from `noxfile.py`).

**Comment by tseaver** [comment]
I've tagged PRs #170, #171, and #172 as blocked on this issue.  Resolving this issue will necessitate doing a manual synth, at which point those PRs should all be closed.

I've tagged PRs #176 and #182 as blocked on this issue, because we should work out how to have `pytypes` checked under CI without blocking synth, before we add more (potentially breaking) typing-related changes.

**Comment by crwilcox** [comment]
I have excluded pytype from CI in a recent PR. https://github.com/googleapis/python-firestore/pull/187/files#diff-ce0d2ea7b6085e6c4bd286d0a15a3971R47

**Comment by tseaver** [comment]
@crwilcox PR #187 actually removed the manual changes applied to generated code to make `pytype` happy, which does unblock further synth.  We still shouldn't move forward on other `pytype`-related changes (PR #176, PR #182),  until we figure out how to get those changes re-applied, ideally via `gapic-generator-python`, or via `synth.py` (as a workaround).

**Comment by crwilcox** [comment]
@tseaver is this still active?

**Comment by tseaver** [comment]
@crwilcox #201 basically fixed it.  I've done another manual synth in #279 to ensure that it remains OK.
