### ISSUE TITLE
Add support for != and not-in queries

### ISSUE THREAD

**Issue by HemangChothani** [googleapis/python-firestore#189]
Porting from [Java](https://github.com/googleapis/java-firestore/pull/350) and [Node](https://github.com/googleapis/nodejs-firestore/pull/1292)

For python auto generated code is missing here  whereas it's generated for java.
https://github.com/googleapis/python-firestore/blob/581520c67340680927148045249bd775487eabac/google/cloud/firestore_v1/types/query.py#L173-L183

@tseaver @crwilcox  Should i run synth.py for that?

**Comment by HemangChothani** [comment]
Found the PR of auto generated code https://github.com/googleapis/python-firestore/pull/171 and it's blocked for now.

**Comment by tseaver** [comment]
PR #187 replaced PR #171.  It [added `NOT_EQUAL` and `NOT_IN`](https://github.com/googleapis/python-firestore/blob/1f44a45419a85d8646ded5f22d6cbab697761651/google/cloud/firestore_v1/types/query.py#L170-L182):

```python
        class Operator(proto.Enum):
            r"""A field filter operator."""
            OPERATOR_UNSPECIFIED = 0
            LESS_THAN = 1
            LESS_THAN_OR_EQUAL = 2
            GREATER_THAN = 3
            GREATER_THAN_OR_EQUAL = 4
            EQUAL = 5
            NOT_EQUAL = 6
            ARRAY_CONTAINS = 7
            IN = 8
            ARRAY_CONTAINS_ANY = 9
            NOT_IN = 10
```
