### ISSUE TITLE
from google.cloud import firestore fails when a binary is dependent on a proto

### ISSUE THREAD

**Issue by cdg720** [googleapis/python-firestore#194]
#### Environment details

  - OS type and version:
 MacOS 10.15.6

  - Python version:
 3.8.5 (default, Jul 21 2020, 10:48:26)
 [Clang 11.0.3 (clang-1103.0.32.62)]

  - pip version: 
pip 20.2.3 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)

  - `google-cloud-firestore` version:
Name: google-cloud-firestore
Version: 1.9.0
Summary: Google Cloud Firestore API client library
Home-page: https://github.com/googleapis/python-firestore
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /Users/x/Library/Python/3.8/lib/python/site-packages
Requires: google-api-core, pytz, google-cloud-core
Required-by: firebase-admin

 - bazel version
bazel 3.5.0-homebrew

#### Steps to reproduce
```
git clone https://github.com/cdg720/bazel_examples.git
cd firestore2
bazel build -c opt foo:bar
```
`./bazel-bin/foo/bar` fails whereas `python3 foo/bar.py` runs.

#### Code example

WORKSPACE
```
### Python proto rules
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "build_stack_rules_proto",
    urls = ["https://github.com/stackb/rules_proto/archive/b2913e6340bcbffb46793045ecac928dcf1b34a5.tar.gz"],
    sha256 = "d456a22a6a8d577499440e8408fc64396486291b570963f7b157f775be11823e",
    strip_prefix = "rules_proto-b2913e6340bcbffb46793045ecac928dcf1b34a5",
)
load("@build_stack_rules_proto//python:deps.bzl", "python_proto_library")
python_proto_library()
load("@io_bazel_rules_python//python:pip.bzl", "pip_import", "pip_repositories")
pip_repositories()
pip_import(
    name = "protobuf_py_deps",
    requirements = "@build_stack_rules_proto//python/requirements:protobuf.txt",
)
load("@protobuf_py_deps//:requirements.bzl", protobuf_pip_install = "pip_install")
protobuf_pip_install()
```
foo/BUILD
```
py_binary(
    name = "bar",
    srcs = ["bar.py"],
    deps = [
        "//protos:empty_py",
    ],
)
```
foo/bar.py
```
import os
import sys

from absl import app
from absl import flags
from google.cloud import firestore


def main(argv):
  print(sys.executable)
  print(sys.version)


if __name__ == "__main__":
  app.run(main)
```
protos/BUILD
```
package(default_visibility = [
    "//foo:__pkg__",
])

load("@build_stack_rules_proto//python:python_proto_library.bzl", "python_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "empty_proto",
    srcs = ["empty.proto"],
)

python_proto_library(
    name = "empty_py",
    deps = [ ":empty_proto" ],
)
```
protos/empty.proto
```
```

#### Stack trace
```
Traceback (most recent call last):
  File "/Users/x/development/bazel_examples/firestore2/./bazel-bin/foo/bar.runfiles/__main__/foo/bar.py", line 6, in <module>
    from google.cloud import firestore
  File "/Users/x/Library/Python/3.8/lib/python/site-packages/google/cloud/firestore.py", line 18, in <module>
    from google.cloud.firestore_v1 import __version__
  File "/Users/x/Library/Python/3.8/lib/python/site-packages/google/cloud/firestore_v1/__init__.py", line 21, in <module>
    from google.cloud.firestore_v1 import types
  File "/Users/x/Library/Python/3.8/lib/python/site-packages/google/cloud/firestore_v1/types.py", line 29, in <module>
    from google.cloud.firestore_v1.proto import common_pb2
  File "/Users/x/Library/Python/3.8/lib/python/site-packages/google/cloud/firestore_v1/proto/common_pb2.py", line 24, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

This also fails on a linux machine with the same error. I have tried swapping out stackb with rules_proto_grpc and the problem persists.

It is probably related to https://github.com/googleapis/python-firestore/issues/19

Thanks,
DK

**Comment by cdg720** [comment]
i think this is a bug in google-cloud-firestore 1.9.0. when i downgraded mine to 1.7.0 it works now.

**Comment by tseaver** [comment]
@cdg720 What version of `protobuf` (the Python library) is being used?  The `_internal_create_key` member is [present since version 3.12.0](https://github.com/protocolbuffers/protobuf/commit/b99994d994e399174fe688a5efbcb6d91f36952a#diff-d6de91caf3b3a819abb247fae7f62938).

**Comment by cdg720** [comment]
@tseaver 

I am using 3.13.0 for protobuf and protoc.

pip3 show protobuf
Name: protobuf
Version: 3.13.0
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: None
Author-email: None
License: 3-Clause BSD License
Location: /usr/local/Cellar/protobuf/3.13.0/libexec/lib/python3.8/site-packages
Requires: six, setuptools
Required-by: tensorflow, tensorboard, googleapis-common-protos, google-api-core

protoc --version
libprotoc 3.13.0

**Comment by tseaver** [comment]
@cdg720 Can you please try the following:

```bash
python -c "from pprint import pprint; from google.protobuf import descriptor; pprint(descriptor.__dict__)"
```

**Comment by cdg720** [comment]
python3 -c "from pprint import pprint; from google.protobuf import descriptor; pprint(descriptor.__dict__)"
{'Descriptor': <class 'google.protobuf.descriptor.Descriptor'>,
 'DescriptorBase': <class 'google.protobuf.descriptor.DescriptorBase'>,
 'DescriptorMetaclass': <class 'google.protobuf.descriptor.DescriptorMetaclass'>,
 'EnumDescriptor': <class 'google.protobuf.descriptor.EnumDescriptor'>,
 'EnumValueDescriptor': <class 'google.protobuf.descriptor.EnumValueDescriptor'>,
 'Error': <class 'google.protobuf.descriptor.Error'>,
 'FieldDescriptor': <class 'google.protobuf.descriptor.FieldDescriptor'>,
 'FileDescriptor': <class 'google.protobuf.descriptor.FileDescriptor'>,
 'MakeDescriptor': <function MakeDescriptor at 0x1023021f0>,
 'MethodDescriptor': <class 'google.protobuf.descriptor.MethodDescriptor'>,
 'OneofDescriptor': <class 'google.protobuf.descriptor.OneofDescriptor'>,
 'ServiceDescriptor': <class 'google.protobuf.descriptor.ServiceDescriptor'>,
 'TypeTransformationError': <class 'google.protobuf.descriptor.TypeTransformationError'>,
 '_Deprecated': <function _Deprecated at 0x101fd39d0>,
 '_Lock': <class 'google.protobuf.descriptor._Lock'>,
 '_NestedDescriptorBase': <class 'google.protobuf.descriptor._NestedDescriptorBase'>,
 '_OptionsOrNone': <function _OptionsOrNone at 0x1023020d0>,
 '_ParseOptions': <function _ParseOptions at 0x1022fcd30>,
 '_ToCamelCase': <function _ToCamelCase at 0x102302040>,
 '_ToJsonName': <function _ToJsonName at 0x102302160>,
 '_USE_C_DESCRIPTORS': True,
 '__author__': 'robinson@google.com (Will Robinson)',
 '__builtins__': {'ArithmeticError': <class 'ArithmeticError'>,
                  'AssertionError': <class 'AssertionError'>,
                  'AttributeError': <class 'AttributeError'>,
                  'BaseException': <class 'BaseException'>,
                  'BlockingIOError': <class 'BlockingIOError'>,
                  'BrokenPipeError': <class 'BrokenPipeError'>,
                  'BufferError': <class 'BufferError'>,
                  'BytesWarning': <class 'BytesWarning'>,
                  'ChildProcessError': <class 'ChildProcessError'>,
                  'ConnectionAbortedError': <class 'ConnectionAbortedError'>,
                  'ConnectionError': <class 'ConnectionError'>,
                  'ConnectionRefusedError': <class 'ConnectionRefusedError'>,
                  'ConnectionResetError': <class 'ConnectionResetError'>,
                  'DeprecationWarning': <class 'DeprecationWarning'>,
                  'EOFError': <class 'EOFError'>,
                  'Ellipsis': Ellipsis,
                  'EnvironmentError': <class 'OSError'>,
                  'Exception': <class 'Exception'>,
                  'False': False,
                  'FileExistsError': <class 'FileExistsError'>,
                  'FileNotFoundError': <class 'FileNotFoundError'>,
                  'FloatingPointError': <class 'FloatingPointError'>,
                  'FutureWarning': <class 'FutureWarning'>,
                  'GeneratorExit': <class 'GeneratorExit'>,
                  'IOError': <class 'OSError'>,
                  'ImportError': <class 'ImportError'>,
                  'ImportWarning': <class 'ImportWarning'>,
                  'IndentationError': <class 'IndentationError'>,
                  'IndexError': <class 'IndexError'>,
                  'InterruptedError': <class 'InterruptedError'>,
                  'IsADirectoryError': <class 'IsADirectoryError'>,
                  'KeyError': <class 'KeyError'>,
                  'KeyboardInterrupt': <class 'KeyboardInterrupt'>,
                  'LookupError': <class 'LookupError'>,
                  'MemoryError': <class 'MemoryError'>,
                  'ModuleNotFoundError': <class 'ModuleNotFoundError'>,
                  'NameError': <class 'NameError'>,
                  'None': None,
                  'NotADirectoryError': <class 'NotADirectoryError'>,
                  'NotImplemented': NotImplemented,
                  'NotImplementedError': <class 'NotImplementedError'>,
                  'OSError': <class 'OSError'>,
                  'OverflowError': <class 'OverflowError'>,
                  'PendingDeprecationWarning': <class 'PendingDeprecationWarning'>,
                  'PermissionError': <class 'PermissionError'>,
                  'ProcessLookupError': <class 'ProcessLookupError'>,
                  'RecursionError': <class 'RecursionError'>,
                  'ReferenceError': <class 'ReferenceError'>,
                  'ResourceWarning': <class 'ResourceWarning'>,
                  'RuntimeError': <class 'RuntimeError'>,
                  'RuntimeWarning': <class 'RuntimeWarning'>,
                  'StopAsyncIteration': <class 'StopAsyncIteration'>,
                  'StopIteration': <class 'StopIteration'>,
                  'SyntaxError': <class 'SyntaxError'>,
                  'SyntaxWarning': <class 'SyntaxWarning'>,
                  'SystemError': <class 'SystemError'>,
                  'SystemExit': <class 'SystemExit'>,
                  'TabError': <class 'TabError'>,
                  'TimeoutError': <class 'TimeoutError'>,
                  'True': True,
                  'TypeError': <class 'TypeError'>,
                  'UnboundLocalError': <class 'UnboundLocalError'>,
                  'UnicodeDecodeError': <class 'UnicodeDecodeError'>,
                  'UnicodeEncodeError': <class 'UnicodeEncodeError'>,
                  'UnicodeError': <class 'UnicodeError'>,
                  'UnicodeTranslateError': <class 'UnicodeTranslateError'>,
                  'UnicodeWarning': <class 'UnicodeWarning'>,
                  'UserWarning': <class 'UserWarning'>,
                  'ValueError': <class 'ValueError'>,
                  'Warning': <class 'Warning'>,
                  'ZeroDivisionError': <class 'ZeroDivisionError'>,
                  '__build_class__': <built-in function __build_class__>,
                  '__debug__': True,
                  '__doc__': 'Built-in functions, exceptions, and other '
                             'objects.\n'
                             '\n'
                             "Noteworthy: None is the `nil' object; Ellipsis "
                             "represents `...' in slices.",
                  '__import__': <built-in function __import__>,
                  '__loader__': <class '_frozen_importlib.BuiltinImporter'>,
                  '__name__': 'builtins',
                  '__package__': '',
                  '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>),
                  'abs': <built-in function abs>,
                  'all': <built-in function all>,
                  'any': <built-in function any>,
                  'ascii': <built-in function ascii>,
                  'bin': <built-in function bin>,
                  'bool': <class 'bool'>,
                  'breakpoint': <built-in function breakpoint>,
                  'bytearray': <class 'bytearray'>,
                  'bytes': <class 'bytes'>,
                  'callable': <built-in function callable>,
                  'chr': <built-in function chr>,
                  'classmethod': <class 'classmethod'>,
                  'compile': <built-in function compile>,
                  'complex': <class 'complex'>,
                  'copyright': Copyright (c) 2001-2020 Python Software Foundation.
All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved.,
                  'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
    for supporting Python development.  See www.python.org for more information.,
                  'delattr': <built-in function delattr>,
                  'dict': <class 'dict'>,
                  'dir': <built-in function dir>,
                  'divmod': <built-in function divmod>,
                  'enumerate': <class 'enumerate'>,
                  'eval': <built-in function eval>,
                  'exec': <built-in function exec>,
                  'exit': Use exit() or Ctrl-D (i.e. EOF) to exit,
                  'filter': <class 'filter'>,
                  'float': <class 'float'>,
                  'format': <built-in function format>,
                  'frozenset': <class 'frozenset'>,
                  'getattr': <built-in function getattr>,
                  'globals': <built-in function globals>,
                  'hasattr': <built-in function hasattr>,
                  'hash': <built-in function hash>,
                  'help': Type help() for interactive help, or help(object) for help about object.,
                  'hex': <built-in function hex>,
                  'id': <built-in function id>,
                  'input': <built-in function input>,
                  'int': <class 'int'>,
                  'isinstance': <built-in function isinstance>,
                  'issubclass': <built-in function issubclass>,
                  'iter': <built-in function iter>,
                  'len': <built-in function len>,
                  'license': Type license() to see the full license text,
                  'list': <class 'list'>,
                  'locals': <built-in function locals>,
                  'map': <class 'map'>,
                  'max': <built-in function max>,
                  'memoryview': <class 'memoryview'>,
                  'min': <built-in function min>,
                  'next': <built-in function next>,
                  'object': <class 'object'>,
                  'oct': <built-in function oct>,
                  'open': <built-in function open>,
                  'ord': <built-in function ord>,
                  'pow': <built-in function pow>,
                  'print': <built-in function print>,
                  'property': <class 'property'>,
                  'quit': Use quit() or Ctrl-D (i.e. EOF) to exit,
                  'range': <class 'range'>,
                  'repr': <built-in function repr>,
                  'reversed': <class 'reversed'>,
                  'round': <built-in function round>,
                  'set': <class 'set'>,
                  'setattr': <built-in function setattr>,
                  'slice': <class 'slice'>,
                  'sorted': <built-in function sorted>,
                  'staticmethod': <class 'staticmethod'>,
                  'str': <class 'str'>,
                  'sum': <built-in function sum>,
                  'super': <class 'super'>,
                  'tuple': <class 'tuple'>,
                  'type': <class 'type'>,
                  'vars': <built-in function vars>,
                  'zip': <class 'zip'>},
 '__cached__': '/usr/local/Cellar/protobuf/3.13.0/libexec/lib/python3.8/site-packages/google/protobuf/__pycache__/descriptor.cpython-38.pyc',
 '__doc__': 'Descriptors essentially contain exactly the information found in '
            'a .proto\n'
            'file, in types that make this information accessible in Python.\n',
 '__file__': '/usr/local/Cellar/protobuf/3.13.0/libexec/lib/python3.8/site-packages/google/protobuf/descriptor.py',
 '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x101ac1b50>,
 '__name__': 'google.protobuf.descriptor',
 '__package__': 'google.protobuf',
 '__spec__': ModuleSpec(name='google.protobuf.descriptor', loader=<_frozen_importlib_external.SourceFileLoader object at 0x101ac1b50>, origin='/usr/local/Cellar/protobuf/3.13.0/libexec/lib/python3.8/site-packages/google/protobuf/descriptor.py'),
 '_internal_create_key': <object object at 0x101c37c80>,
 '_lock': <unlocked _thread.lock object at 0x101fdf540>,
 '_message': <module 'google.protobuf.pyext._message' from '/usr/local/Cellar/protobuf/3.13.0/libexec/lib/python3.8/site-packages/google/protobuf/pyext/_message.cpython-38-darwin.so'>,
 'api_implementation': <module 'google.protobuf.internal.api_implementation' from '/usr/local/Cellar/protobuf/3.13.0/libexec/lib/python3.8/site-packages/google/protobuf/internal/api_implementation.py'>,
 'binascii': <module 'binascii' from '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/binascii.cpython-38-darwin.so'>,
 'os': <module 'os' from '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py'>,
 'six': <module 'six' from '/usr/local/lib/python3.8/site-packages/six.py'>,
 'threading': <module 'threading' from '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py'>,
 'warnings': <module 'warnings' from '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/warnings.py'>}

**Comment by tseaver** [comment]
I can't reproduce your issue (missing `_internal_create_key`) in a fresh virtual environment:

```bash
$ python3.8 -m venv /tmp/fs-194

$ /tmp/fs-194/bin/pip install "protobuf
...
Successfully installed protobuf-3.13.0 six-1.15.0

$ /tmp/fs-194/bin/python -c "from google.protobuf import descriptor; print(descriptor._internal_create_key)"
<object object at 0x7fec40b35ec0>
```

And in fact, I see that `_internal_create_key` is present in the module dict output you posted.  Somehow, your Bazel build must be installing an older version (pre-3.12.0) of the `protobuf` distribution than the one you are importing.

**Comment by cdg720** [comment]
I was able to reproduce this error on google cloud shell.
```
pip3 show protobuf
Name: protobuf
Version: 3.13.0
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: None
Author-email: None
License: 3-Clause BSD License
Location: /usr/local/lib/python3.7/dist-packages
Requires: setuptools, six
Required-by: tensorflow, tensorboard, proto-plus, googleapis-common-protos, google-api-core
```

```
pip3 show google-cloud-firestore
Name: google-cloud-firestore
Version: 1.9.0
Summary: Google Cloud Firestore API client library
Home-page: https://github.com/googleapis/python-firestore
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /home/admin_/.local/lib/python3.7/site-packages
Requires: google-cloud-core, google-api-core, pytz
Required-by:
```

```
bazel --version
bazel 3.5.0
```

```
python3 --version
Python 3.7.3
```

```
pip3 --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
```

```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Building the binary is just really slow...

**Comment by cdg720** [comment]
You are right.

bazel is installing older version 3.6.1.

I added the following in my code.
```
from importlib.metadata import version
print(version('protobuf'))
```

With `python3 foo/bar.py`, I get 3.13.0 but with `./bazel-bin/foo/bar`, I get 3.6.1.

**Comment by cdg720** [comment]
When I replaced stackb whose [requirements](https://github.com/stackb/rules_proto/blob/master/python/requirements.txt) has `protobuf==3.7.1` with rules-proto-grpc, I get 3.13.0 with bazel build. (I am still looking why I was getting 3.6.1 though.)

```
from importlib.metadata import version

from absl import app
from absl import flags
from google.protobuf import descriptor


def main(argv):
  print('protobuf version', version('protobuf'))
  print('firestore version', version('google-cloud-firestore'))
  print('_internal_create_key' in descriptor.__dict__)
  print(descriptor._internal_create_key)


if __name__ == "__main__":
  app.run(main)
```

By executing above code, `python3 foo/bar.py` outputs
```
protobuf version 3.13.0
firestore version 1.7.0
True
<object object at 0x106d98e30>
```
whereas `./bazel-bin/foo/bar` gets me
```
protobuf version 3.13.0
firestore version 1.7.0
False
Traceback (most recent call last):
  File "/Users/x/development/bazel_examples/firestore2/./bazel-bin/foo/bar.runfiles/__main__/foo/bar.py", line 16, in <module>
    app.run(main)
  File "/Users/x/Library/Python/3.8/lib/python/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/Users/x/Library/Python/3.8/lib/python/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/Users/x/development/bazel_examples/firestore2/./bazel-bin/foo/bar.runfiles/__main__/foo/bar.py", line 12, in main
    print(descriptor._internal_create_key)
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```
which doesn't make sense to me.

**Comment by cdg720** [comment]
In my WORKSPACE I had
```
pip_import(
    name = "protobuf_py_deps",
    requirements = "@build_stack_rules_proto//python/requirements:protobuf.txt",
)

load("@protobuf_py_deps//:requirements.bzl", protobuf_pip_install = "pip_install")
```
which installs protobuf 3.6.1. https://github.com/stackb/rules_proto/blob/master/python/requirements/protobuf.txt 

Once I changed the requirements, my problem goes away.
