### ISSUE TITLE
Add method createImplicitOrderBy for ineqaulity filters

### ISSUE THREAD

**Issue by HemangChothani** [googleapis/python-firestore#203]
Found this method in [java](https://github.com/googleapis/java-firestore/blob/3846f5cd6078e82fc2bd51e00e3dcea97b31594e/google-cloud-firestore/src/main/java/com/google/cloud/firestore/Query.java#L322) and [node](https://github.com/googleapis/nodejs-firestore/blob/46c7dff3274318370286ff3bfa3358a46c064de3/dev/src/reference.ts#L1465) which called in startAt, startAfter, endAt, endAfter functions but did't found similar in python, Also asked in this [issue](https://github.com/googleapis/python-firestore/issues/56#issuecomment-639676857) but at that time i misjudged the thing.

@crwilcox  @tseaver Is that functionality needed for python?

**Comment by tseaver** [comment]
`BaseQuery` has [methods](https://github.com/googleapis/python-firestore/blob/master/google/cloud/firestore_v1/base_query.py#L523-L652) `start_at`, `start_after`, `end_at`, `end_before`.

There is an explicit, documented requirement that all fields of cursors passed to those methods (or to the constructor) have matching entries in the query's `order_by` field.  `BaseQuery._normalize_cursor` [raises ValueError](https://github.com/googleapis/python-firestore/blob/dffc580472193c7d3b0eecadc316d77afaa0d0bf/google/cloud/firestore_v1/base_query.py#L753) if that constratint is not met.

This issue would be a feature request to have `_normalize_cursor` synthesize the `order_by` bits, or else have the cursor-setting methods somehow implicitly set the order.  I don't like the latter, as it requires guessing about `ASCENDING` / `DESCENDING`, and presumes that the order in which the methods are called should somehow dictate the sort order for the query.

**Comment by meredithslota** [comment]
Recategorizing as a feature request but it's not clear if this should actually be done or the relative priority.
