### ISSUE TITLE
Field path not interpreted as expected when created with a segment starting with numeral

### ISSUE THREAD

**Issue by dooinwell** [googleapis/python-firestore#213]
(Using latest Python and Google APIs versions as available on GAE)

`from google.cloud import firestore`
`my_dic = {'a_key':'44D-EAA-555'}`
`db = firestore.Client()`
`db.collection(u'my_collection').document(u'my_document').set({db.field_path('my_string', my_dic['a_key'],'my_string2'):True}, merge=True)`

will result in the following field being created: 
>my_string.\`44D-EAA-555\`.my_string2

while I would expect the following field (map) to be created: 
>my_string

with the following nested field  
>44D-EAA-555

**Comment by HemangChothani** [comment]
@dooinwell Please go through the comments of https://github.com/googleapis/python-firestore/issues/10 issue as both are same issue.

Here is the [doc](https://firebase.google.com/docs/firestore/quotas#limits) of limitation and see the `Constraints on field paths` part in doc.

**Comment by dooinwell** [comment]
Hi @HemangChothani - Thank you for reviewing. I'm aware but was expecting that using the field_path constructor was precisely a way to get that arranged for me if needed - rather than naively concatenating strings with an in-between dot. 

But I admit the documentation is not absolutely explicit on this behavior: https://googleapis.dev/python/firestore/latest/field_path.html

If not intended to work this way, it does not seem like it would be a luxury to have a robust field path constructor for situation where the developer has no direct control on what special characters may be in a field name. And also, having a starting digit should maybe not be an issue at all. 
Additionally, I would expect the constructor to fail rather than produce an error-prone output.

**Comment by dooinwell** [comment]
Also, the resulting field name does seem to show an escaping backtick that the constructor placed there. Not clear why it then gets ignored when updating the field.

**Comment by HemangChothani** [comment]
@tseaver @crwilcox Need an opinion.
Should we need to through an  error `(ValueError)`  when find `field_path` key starts with the number or just update the `documentation` about limitation of the field_path starting with number.

**Comment by tseaver** [comment]
@dooinwell The semantics you are expecting when using a field path are only supported for `Document.update` (see its [docs](https://googleapis.dev/python/firestore/latest/document.html#google.cloud.firestore_v1.document.DocumentReference.update)), and not for `Document.set` (see its [docs](https://googleapis.dev/python/firestore/latest/document.html#google.cloud.firestore_v1.document.DocumentReference.set)).
