### ISSUE TITLE
Expose retry, timeout parameters in manual surface

### ISSUE THREAD

**Issue by crwilcox** [googleapis/python-firestore#221]
the generated surface surfaces retry and timeout. For many calls this would be useful for firestore customers.
```
def run_query(
        self,
        request: firestore.RunQueryRequest = None,
        *,
        retry: retries.Retry = gapic_v1.method.DEFAULT,
        timeout: float = None,
        metadata: Sequence[Tuple[str, str]] = (),
    ) -> Iterable[firestore.RunQueryResponse]:
```

Async and Sync clients should be updated to expose this.

**Comment by tseaver** [comment]
@crwilcox API design questions:

-  How should `retry` and `timeout` options be surfaced when using `Batch` or `Transaction` as context managers?
- Should the normally-invisible `Transaction._begin` and `Transaction._rollback` methods somehow pass through `retry` / `timeout`?
