### ISSUE TITLE
Buildozer no module named google.cloud when deploying to Android

### ISSUE THREAD

**Issue by callumpurcell1** [googleapis/python-firestore#226]
Even after adding google-cloud-firestore and a host of other Google requirements to the buildozer.spec file requirements section I still get an error saying no module named google.cloud

**Comment by crwilcox** [comment]
Hi @callumpurcell1 this isn't enough information for us to reproduce and provide assitance. Could your provide additional information? Where are you installing the library? how are you installing the library?

Without anything else, it seems like you may be vendoring and having issues with namespace packging?

**Comment by tseaver** [comment]
@callumpurcell1 Please feel free to reopen / follow up if you can provide more information.

**Comment by callumpurcell1** [comment]
Apologies, this problem sorted itself. I did buildozer android clean a couple of times and no longer had the issue. I'm now onto the next issue with Buildozer + Firebase as to why my grcpio custom recipe isn't working!
