### ISSUE TITLE
Getting around firestore's 1MB limit for array fields

### ISSUE THREAD

**Issue by skgbanga** [googleapis/python-firestore#246]
Consider the following:

> Collection Name: Applications
> Documents: A, B, C, D
> Each document has fields 'location', 'users'
> users is a list.

```
[
  'A':
     - 'location': 'NY'
     - 'users': [
        'id1',
        'id2',
        'id3',
        'id4'
     ]
  'B':
     - 'location': 'NY'
     - 'users': [
        'id1',
        'id7',
     ]
  'C':
    - 'location': 'CA'
    - 'users':
        'id2',
        'id20',
        'id21'
    ]
  'D': {
    - 'location': 'NY'
    - 'users': [
        'id1',
        'id11',
        'id12',
        'id4'
    ]
]
```

One can do a query "Get all applications which user  `id1`" uses as:

```
for doc in collection.where('users', 'array_contains', 'id1').stream():
  print(doc.id, end=' ')
```

This should print
> A B D

Now as the number of users increase for each application, they will slowly start violating firestore's 1MB limit.

The solution that has been proposed for this to NOT to use `users` as a field, but as a collection.

```
[
  'A':
     - 'location': 'NY'
     'users':
        - 'id1'
        - 'id2'
        - 'id3'
        - 'id4'
...
]
```

Now `users` is a collection within document 'A' which has 'id1', 'id2'... as documents.

My question now is: How should I write my query such that I can still get back top level restaurant documents?
In https://firebase.google.com/docs/firestore/query-data/queries, it is given that one can make a `CollectionGroup`,
but I don't think that solves my problem since it will give me documents of those collections, and not the top level documents that I am seeking.

**Comment by HemangChothani** [comment]
@skgbanga You need to use 'CollectionGroup' for that here is the example to retrieve parent collection and document id:

```python
from google.cloud import firestore

db = firestore.Client()
cities = db.collection(u'cities')

sf_landmarks = cities.document(u'SF').collection(u'landmarks')
sf_landmarks.document().set({
    u'name': u'Golden Gate Bridge',
    u'type': u'bridge'
})
sf_landmarks.document().set({
    u'name': u'Legion of Honor',
    u'type': u'museum'
})
la_landmarks = cities.document(u'LA').collection(u'landmarks')
la_landmarks.document().set({
    u'name': u'Griffith Park',
    u'type': u'park'
})
la_landmarks.document().set({
    u'name': u'The Getty',
    u'type': u'museum'
})
dc_landmarks = cities.document(u'DC').collection(u'landmarks')
dc_landmarks.document().set({
    u'name': u'Lincoln Memorial',
    u'type': u'memorial'
})
dc_landmarks.document().set({
    u'name': u'National Air and Space Museum',
    u'type': u'museum'
})
tok_landmarks = cities.document(u'TOK').collection(u'landmarks')
tok_landmarks.document().set({
    u'name': u'Ueno Park',
    u'type': u'park'
})
tok_landmarks.document().set({
    u'name': u'National Museum of Nature and Science',
    u'type': u'museum'
})
bj_landmarks = cities.document(u'BJ').collection(u'landmarks')
bj_landmarks.document().set({
    u'name': u'Jingshan Park',
    u'type': u'park'
})
bj_landmarks.document().set({
    u'name': u'Beijing Ancient Observatory',
    u'type': u'museum'
})

museums = db.collection_group(u'landmarks')\
    .where(u'type', u'==', u'museum')
docs = museums.stream()
for doc in docs:
    print ("Path: ", doc.reference.path)
    print ("Parent: ", doc.reference.parent.parent.id)
    print(f'{doc.id} => {doc.to_dict()}')
```

Output:

    Path: cities/BJ/landmarks/MlkINIStmVPVUedAd9nb
    Parent:  BJ
    MlkINIStmVPVUedAd9nb => {'type': 'museum', 'name': 'Beijing Ancient Observatory'}
    Path: cities/DC/landmarks/XUfBFADw0F1XocUMDMko
    Parent:  DC
    XUfBFADw0F1XocUMDMko => {'name': 'National Air and Space Museum', 'type': 'museum'}
    Path: cities/LA/landmarks/7lIQVwCEczK1HJkZYRyr
    Parent:  LA
    7lIQVwCEczK1HJkZYRyr => {'name': 'The Getty', 'type': 'museum'}
    Path: cities/SF/landmarks/d6zSFTKOEiUVT4C2A8oW
    Parent:  SF
    d6zSFTKOEiUVT4C2A8oW => {'type': 'museum', 'name': 'Legion of Honor'}
    Path: cities/TOK/landmarks/fJPUnXDogwWjbBjFK8Hr
    Parent:  TOK
    fJPUnXDogwWjbBjFK8Hr => {'name': 'National Museum of Nature and Science', 'type': 'museum'}

**Comment by tseaver** [comment]
@skgbanga Please feel free to reopen / follow up if @HemangChothani's answer is not sufficient.
