### ISSUE TITLE
add support for missing operators '!=' and 'not-in'

### ISSUE THREAD

**Issue by joechip504** [googleapis/python-firestore#249]
Hi python-firestore team,

These operators are available using other client libraries (javascript, java, objective c) but they are not available using the python client.

https://firebase.google.com/docs/firestore/query-data/queries#not_equal
The documentation here says `// Snippet not yet available` when you select python. If you try to use them anyway (which I did :wink: ) the client throws a `ValueError`

Are there plans to add these operators in a future release?

Using google-cloud-firestore==1.9.0:
```python
db = firestore.Client()
db.collection('colors').where('color', '!=', 'red')
# >>> ValueError: Operator string '!=' is invalid. Valid choices are: <, <=, ==, >, >=, array_contains, array_contains_any, in

colors = ['red', 'white', 'blue']
db.collection('colors').where('color', 'not-in', colors)
# >>> ValueError: Operator string '!=' is invalid. Valid choices are: <, <=, ==, >, >=, array_contains, array_contains_any, in
```

Cheers,
Joe

**Comment by joechip504** [comment]
Aha I see these were recently added: https://github.com/googleapis/python-firestore/commit/1d09f21f6c8cb7f69f0e30a960418f0f6899aa01 

Will try out the pre-release version and see what happens
https://pypi.org/project/google-cloud-firestore/2.0.0.dev2/

**Comment by HemangChothani** [comment]
Closing this issue for now, feel free to re-open.
