### ISSUE TITLE
Python-Firestore API Documentation

### ISSUE THREAD

**Issue by martindufort** [googleapis/python-firestore#262]
Hi, 

We are currently integrating Cloud Firestore (using the Python client) into one of our project. 

However we have some difficulties grasping all the capabilities because it seems the API documentation [here](https://googleapis.dev/python/firestore/latest/index.html) is incomplete.

I have to resort to browsing the GitHub source code to grasp which methods are available to perform a specific behavior.

Example: In the API Documentation there is no reference to `class DocumentSnapshot` I could find. 

Some of the questions, I was asking myself:
_How do I get a DocumentReference from a DocumentSnapshot instance ?_ 

I had to browse the `class DocumentSnapshot` source code and find that the property `reference` was available for that. 

Let me know if I'm not looking at the proper location. 
Thanks for your support.

**Comment by martindufort** [comment]
Is the public documentation web page now reflecting all classes ?

**Comment by HemangChothani** [comment]
Yes, i think only `DocumentSnapshot` class was missing.

**Comment by tseaver** [comment]
Nope.  Please see 9fdad0c (part of PR #279) for other cases where the "async split" left classes undocumented.

**Comment by martindufort** [comment]
I'm looking here https://googleapis.dev/python/firestore/latest/document.html and I don't see `DocumentSnaphot` documentation.

**Comment by HemangChothani** [comment]
@martindufort `DocumentSnaphot` is added in https://github.com/googleapis/python-firestore/pull/263 PR, waiting for merge.

**Comment by HemangChothani** [comment]
@tseaver  I was not aware about exposing the documentation of async classes.

**Comment by martindufort** [comment]
> @martindufort `DocumentSnaphot` is added in #263 PR, waiting for merge.

Any timeline in closing this PR ?

**Comment by 1337SEnergy** [comment]
there seems to be many more issues with the documentation, for example the documentation for

```
DocumentChange
```
says there are document, target_ids and removed_target_ids fields, however from my inspection there are document, old_index, new_index and type fields instead... 

as mentioned by @martindufort, I have to rely on code inspection to fully grasp how this library actually works, as the documentation is of very little help
