### ISSUE TITLE
Firestore: Problem with pagination with "in" query

### ISSUE THREAD

**Issue by dorli** [googleapis/python-firestore#28]
Hi Folks,
Trying to implement pagination with "in" query raise the following error: `"order by clause cannot contain a field with an equality filter category"`

#### Environment details

OS type and version: `Mac OS X - 10.15.3` and also `AppEngine`
3. Python version and virtual environment information: `Python 3.7.5`
4. google-cloud-firestore version:  `1.6.2`

#### Steps to reproduce

  1. Just try to have query with "start_at" (or "start_after") and a "in" query.

#### Code example

```python
def firestore_pagination_in_query_problem(db):

    # Setup test data.
    for i in range(10):
        db.collection("test-data").document().create({"category": "c1"})

    # First Query.
    results = [
        snapshot
        for snapshot in db.collection("test-data")
        .limit(4)
        .where("category", "in", ["c1"])
        .stream()
    ]
    last_snap = results[-1]

    try:
        # Second Query.
        results = [
            snapshot
            for snapshot in db.collection("test-data")
            .limit(4)
            .where("category", "in", ["c1"])
            .start_at(last_snap)
            .stream()
        ]

    except Exception:
        print_exc()
    finally:
        # Cleanup test data.
        for snapshot in db.collection("test-data").stream():
            snapshot.reference.delete()
```

#### Stack trace
```
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "order by clause cannot contain a field with an equality filter category"
	debug_error_string = "{"created":"@1584605000.505801000","description":"Error received from peer ipv4:[..]:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"order by clause cannot contain a field with an equality filter category","grpc_status":3}"
```

**Comment by plamut** [comment]
@dorli Moved the issue into the new repository.

**Comment by IlyaFaer** [comment]
@dorli, `startAt()` (and similar methods) works little bit different than traditional offsets. `startAt()` gives you an opportunity to offset some **sorted** data, and start fetching results from the specific value. That means, first of all you should sort your data.

If you have docs like:
```
id title
-------
6 "gdfg"
1 "kfgh"
4 "jkdfg"
2 "gadfdf"
```
And you're calling:
```
query.order_by("id').startAt(4)
```
Then you'll first sort them:
```
id title
-------
1 "kfgh"
2 "gadfdf"
4 "jkdfg"
6 "gdfg"
```
And then will take data starting with `4` - offsetting 1 and 2:
```
id title
-------
4 "jkdfg"
6 "gdfg"
```
And if you want to *start at* several values, you should sort results by them. Take a look at the [docs](https://firebase.google.com/docs/firestore/query-data/query-cursors).

**Comment by dorli** [comment]
@IlyaFaer Thank you for your replay, i think i understand what you wrote about the sorted data, my original code has an `order_by` in the query, but i still see the same error.

This doesn't work:

```python
    for i in range(10):
        db.collection("test-data").document().create({"category": "c1", "index": i})

    results = [
        snapshot
        for snapshot in db.collection("test-data")
        .limit(4)
        .order_by("index")
        .where("category", "in", ["c1"])
        .stream()
    ]
    last_snap = results[-1]

    results = [
        snapshot
        for snapshot in db.collection("test-data")
        .limit(4)
        .order_by("index")
        .where("category", "in", ["c1"])
        .start_at(last_snap)
        .stream()
    ]
```

But this those:
```python
    for i in range(10):
        db.collection("test-data").document().create({"category": "c1", "index": i})

    results = [
        snapshot
        for snapshot in db.collection("test-data")
        .limit(4)
        .order_by("index")
        .where("category", "==", "c1")
        .stream()
    ]
    last_snap = results[-1]

    results = [
        snapshot
        for snapshot in db.collection("test-data")
        .limit(4)
        .order_by("index")
        .where("category", "==", "c1")
        .start_at(last_snap)
        .stream()
    ]
```

**Comment by IlyaFaer** [comment]
I've tried your code on a live service - I think, I see the root of your error. Into `start_at()` you're passing a snapshot, which actually includes two fields: `index` and `category`. This `category` field causes the exception. Here is how it worked on my PC;
```python
 results = [
        snapshot
        for snapshot in db.collection("test-data")
        .where("category", "in", ["c1", "c2"])
        .order_by("index")
        .limit(4)
        .stream()
    ]
    last_ind = results[-1].get("index")

    results = [
        snapshot
        for snapshot in db.collection("test-data")
        .limit(4)
        .where("category", "in", ["c1"])
        .order_by("index")
        .start_after({"index": last_ind})
        .stream()
    ]
```
So, I'm using not the whole snapshot from the last page, but only its `index` field.

![image](https://user-images.githubusercontent.com/26030071/77310765-ec9ef980-6d0f-11ea-9ec1-981c0f50ce86.png)

P.S. I assume, it's better to use `start_after()` in your case, as with `start_at()` query will return the last doc from the last page once again.

**Comment by dorli** [comment]
@IlyaFaer Using a dict based cursor with ```FieldPath.document_id()``` i was able to solve my use case.

I ended duplicating some of the code from ```query.py``` so may i suggest that snapshot based cursor will just filtered out fields with ```in query``` like i think it dose for ```array_contains``` queries.

Thank you for your help.
