### ISSUE TITLE
Unusual TypeError: __init__() got an unexpected keyword argument 'client_options

### ISSUE THREAD

**Issue by adityaprakash-bobby** [googleapis/python-firestore#284]
I am getting the below exception which I did not get earlier like 10-12 days back.

#### Environment details

  - OS type and version: Linux 5.4.0-58-generic ~18.04.1-Ubuntu  x86_64 x86_64 x86_64 GNU/Linux
  - Python version: `Python 3.6.9`
  - pip version: `pip 20.1.1 from /home/aditya/Documents/.env/lib/python3.6/site-packages/pip (python 3.6)`
  - `google-cloud-firestore` version: `2.0.2`

#### Steps to reproduce

  1. import firestore
  2. initialize a client

#### Code example

```python
from google.cloud import firestore_v1 as firestore
firestore_client = firestore.Client()

# at the above line it raises the exception which used to not happen few days back
```

#### Stack trace
```
Traceback (most recent call last):
  File "fireStore.py", line 21, in <module>
    db = firestore.Client(project="my-project")
  File "/home/aditya/Documents/.env/lib/python3.6/site-packages/google/cloud/firestore_v1/client.py", line 94, in __init__
    client_options=client_options,
  File "/home/aditya/Documents/.env/lib/python3.6/site-packages/google/cloud/firestore_v1/base_client.py", line 128, in __init__
    _http=None,
TypeError: __init__() got an unexpected keyword argument 'client_options'
```

Thanks!

**Comment by HemangChothani** [comment]
@adityaprakash-bobby  I think you are using old version of `google-cloud-core` please update and try it again, if it doesn't resolve the issue then please share dependency list. `pip3 list` is the command.

**Comment by craiglabenz** [comment]
I was able to recreate this issue on `google-cloud-core==1.3.0` and `google-cloud-firestore==2.0.2`, but the incompatibility disappears after an update of `google-cloud-core` to `1.4` or `1.5`, as @HemangChothani guessed.
