### ISSUE TITLE
Pip install on Apple Silicon M1

### ISSUE THREAD

**Issue by bactisme** [googleapis/python-firestore#285]
There is an issue not directly related to Python Firestore, but the gRPC library, used by python-firestore.

pip install google-cloud-firestore fails on an Apple Silicon M1 processor.

https://github.com/grpc/grpc/issues/25082 

* I am making this ticket in order so python-firestore dev can follow.
* Maybe guys could help or give greater visibility to this issue ? 

#### Environment details

  - OS type and version: Mac OS Big Sur 11.1 on **Apple Silicon M1**.
  - Python version: Python 3.8.2
  - pip version: pip 19.2.3
  - `google-cloud-firestore` version: not installable

**Comment by bactisme** [comment]
I got it working with the version shipped as a wheel on the repo [tensorflow_macos](https://github.com/apple/tensorflow_macos) (commands [here](https://github.com/apple/tensorflow_macos/issues/46))

**Comment by bactisme** [comment]
I got it working with the wheel version shipped on this repo : [tensorflow_macos](https://github.com/apple/tensorflow_macos/releases/tag/v0.1alpha1) - commands [here](https://github.com/apple/tensorflow_macos/issues/46).

**Comment by crwilcox** [comment]
@bactisme thanks. If the gRPC team is aware I am sure they can prioritize. The pin for python firestore is > 1.29 < 2.0, and I don't imagine providing wheels for grpc to target M1 will result in a breaking change. As there is nothing to be done on this library at this time, i am closing this issue.

Thanks.

**Comment by florianmuetzel** [comment]
Same issue here. Please provide fix!

**Comment by crwilcox** [comment]
https://github.com/grpc/grpc/issues/25082 shows that 1.35 versions of grpc should have wheels published for the M1 platform.
