### ISSUE TITLE
Async Client Commit raises TypeError: Unexpected type of call <class 'google.cloud.firestore_v1.types.firestore.CommitResponse'> under emulator

### ISSUE THREAD

**Issue by crwilcox** [googleapis/python-firestore#286]
branching from https://github.com/googleapis/python-firestore/issues/64#issuecomment-749107053

Thank you @mr-bjerre 

Really appreciate the new support of `AsyncClient` !

One issue though. It doesn't work with the firestore emulator. The following script raises and exception

```python
TypeError: Unexpected type of call <class 'google.cloud.firestore_v1.types.firestore.CommitResponse'>
```

Start the firestore emulator and run the script

```python
import asyncio
from google.cloud.firestore import AsyncClient
import os


os.environ["FIRESTORE_EMULATOR_HOST"] = "localhost:8080"

client = AsyncClient()


async def save():
    return (
        await client.collection("test")
        .document("test")
        .set({"message": "Hello World!"})
    )


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(save())
```

The same issue goes for retrieving data.

**Comment by crwilcox** [comment]
Note, this only occurs under emulation.

**Comment by crwilcox** [comment]
```
Exception has occurred: TypeError
Unexpected type of call <class 'google.cloud.firestore_v1.types.firestore.CommitResponse'>
  File "/Users/crwilcox/workspace/python-firestore/google/cloud/firestore_v1/services/firestore/async_client.py", line 691, in commit
    response = await rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/Users/crwilcox/workspace/python-firestore/google/cloud/firestore_v1/async_batch.py", line 58, in commit
    commit_response = await self._client._firestore_api.commit(
  File "/Users/crwilcox/workspace/python-firestore/google/cloud/firestore_v1/async_document.py", line 127, in set
    write_results = await batch.commit(**kwargs)
  File "/Users/crwilcox/scratch/python-firestore/watch.py", line 13, in document_set
    await async_client.collection("test").document("test").set({"message": "Hello World!"})
  File "/Users/crwilcox/scratch/python-firestore/watch.py", line 17, in <module>
    loop.run_until_complete(document_set())
    ```

**Comment by crwilcox** [comment]
I am marking this issue as external and have opened an issue against the api-core package. can close once resolved.

**Comment by joakimnordling** [comment]
Is there any estimation when we could see a release that would include the fix for this issue?

**Comment by adamserafini** [comment]
If I'm understanding the thread of issues correctly, it seems this PR fixes the issue right? But not sure when it will be "released", I am not clear on that https://github.com/googleapis/python-firestore/pull/288

Would also be keen to know when emulator will be released that will work with `asyncio` (we even decided to avoid the `asyncio` client completely in Firestore until it works).

**Comment by crwilcox** [comment]
v2.1.0 was released yesterday: https://pypi.org/project/google-cloud-firestore/

If you see an issue after upgrading with the emulator, please open an issue :)
