### ISSUE TITLE
Incorrect type hints in collection()

### ISSUE THREAD

**Issue by mbrancato** [googleapis/python-firestore#289]
#### Environment details

  - OS type and version: MacOS
  - Python version: Python 3.7.7
  - `google-cloud-firestore` version: 2.0.2

At some point recently the type hints for for `Client().collection()` methods were changed, and they do not reflect examples or the docs. I'm getting type hint warnings.
https://github.com/googleapis/python-firestore/blob/30bb3fb5c36648d3b8acf76349a5726d7a5f135d/google/cloud/firestore_v1/client.py#L120

Should the type hint be changed to simply `str` ? All the comments and docs show these:

```python
client.collection('top')
client.collection('mydocs/doc/subcol')
client.collection('mydocs', 'doc', 'subcol')
```

None of these are `Tuple[str]`. The argument `*collection_path` will produce a tuple when called, but it is called with strings.

**Comment by tseaver** [comment]
Per the implementation, the `collection_path` argument can be either a single, slash-delimited path string, *or* a `Tuple[str]`.  See the [`_path_helper` function(https://github.com/googleapis/python-firestore/blob/29c637490e43db59529edcd3b61ccfca383eb223/google/cloud/firestore_v1/base_client.py#L580), which also has an incorrect typespec for its argument.

**Comment by tseaver** [comment]
A correction:  the leading asterisk (`*collection_path`) means that the value received by the function will *always* be a tuple, and we require that the elements of the tuple be strings.  The *caller* may pass a single string, e.g. `client.collection("mydocs/doc/subcol")`, which will be split on the slashes, exactly as if the caller had passed `client.collection("mydocs", "doc", "subcol")`.  That example is from the [docstring of `Client.collection`](https://github.com/googleapis/python-firestore/blob/29c637490e43db59529edcd3b61ccfca383eb223/google/cloud/firestore_v1/client.py#L133-L135).

**Comment by tseaver** [comment]
OK, looking at [PEP 484](https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values), it appears that `*args` should be typed as the type of one element.
