### ISSUE TITLE
Missing docs for Firebase Admin 

### ISSUE THREAD

**Issue by mik-laj** [googleapis/python-firestore#30]
Hello,

The documentation has serious defects. It has no documentation for FirestoreAdminClient
https://github.com/googleapis/python-firestore/blob/master/google/cloud/firestore_admin_v1/__init__.py#L36-L38
We only have documentation for FirestoreClient.

Best regards,

**Comment by HemangChothani** [comment]
I think this is related to a `gapic`  as it is auto-generated therefore their docs are also auto generated  by `artman`. @crwilcox  can you assign this to a responsible person or can i filed an  issue against the generator.

**Comment by turbaszek** [comment]
@HemangChothani @crwilcox any progress on this one?
