### ISSUE TITLE
Snapshot method for async collections

### ISSUE THREAD

**Issue by Kyzegs** [googleapis/python-firestore#301]
Is there a reason why the async collections do not have `on_snapshot`? And are there any plans to add this?

**Comment by tseaver** [comment]
@Kyzegs You ask a good question.  I believe that the design of `Collection.on_snapshot` / `Query.on_snapshot` (start a background thread which invokes a callback thread "forever" or until cancelled) wasn't seen as a great fit for the current async pattern:  in the async world, one would likely expect instead to have an async method which yielded the "snapshot" objects (sets of added / updated / removed / deleted documents).

**Comment by tseaver** [comment]
Note that adding async support for the `Watch` mechanism is an existing feature request: #131
