### ISSUE TITLE
Snapshot listeners require extremely long initial load time on large collections when used inside a container

### ISSUE THREAD

**Issue by MaticConradi** [googleapis/python-firestore#303]
Snapshot listener performance when initially creating it is extremely slow (talking in terms of requiring up to an hour to return any data) when watching a collection with a large number of documents. The documentation advizes against large documents, but not against large collections. I'm not sure what qualifies as *large*, but mine usually have 5 fields with a couple of subfields, only saving a few numbers and IDs.

#### Environment details

  - OS type and version: Container optimised OS
  - Python version: 3.8.5
  - pip version: 20.2.4
  - `google-cloud-firestore` version: 2.0.2

#### Steps to reproduce

  1. Create a large collection of documents (5000+) with a few fields
  2. Create a snapshot listener
  3. Deploy inside a Docker container

**Comment by crwilcox** [comment]
Initializing a listen/watch requires getting the current context, so it is transmitting all of that data. is this any slower than querying all of that information?

**Comment by MaticConradi** [comment]
I just wrote a dummy script that tests for this, and it looks like the same snapshot listener performed fine in an isolated environment. After some digging I have decided to run my test script inside Docker alongside all other scripts, and that seems to be the issue.

This still sounds like a problem though, why would a container inhibit such a hit to performance (from 10 seconds outside to 10+ minutes inside a container) when nothing has been done with the network configuration on my local machine and GKE.

**Comment by MaticConradi** [comment]
I'm happy to provide more info to resolve this. At the moment, this seems to be happening exclusively in a containerized environment. The same test script has been performing normally when running manually.

**Comment by crwilcox** [comment]
This is interesting and would be interesting to get a closer look at. Have you profiled this at all? For instance, have you narrowed down that it is happening on listen, and not on creation of a client?

Are you doing multiple runs in your cluster? On the same machine? Threaded or multiple processes? or is the scale local and in container identical?

**Comment by MaticConradi** [comment]
I haven't done much profiling, but I can verify this happens on listen, and not on client creation. I'm only running one pod with three listeners, since the performance got significantly worse as the number of replicas went up. The local tests inhibited the same behaviour, and were on the same scale (even though that was technically not the case), so connecting to the same collection in the same database (both inside a container and when running manually). The script is pretty much a just listener with a few worker threads for pulling cached data via ZeroMQ.

I haven't tested one more thing however: the script runs alongside another pod with contains a Discord bot. It could be that Discord.py library is somehow interfeering. I'll post an update when I verify wether that is the case

**Comment by MaticConradi** [comment]
Update: Discord.py doesn't interfeere, running only the database service still has the same amount of lag. Looks like containerized environment is the only apparent cause.

**Comment by MaticConradi** [comment]
Another observation is that the CPU usage goes up to 1 and stays there for the period of waiting for the listener to return initial data.

<img width="437" alt="Screenshot 2021-02-15 at 14 14 54" src="https://user-images.githubusercontent.com/5693961/107951195-3e8be600-6f98-11eb-8e55-e3c1bd502ee6.png">

**Comment by MaticConradi** [comment]
For some reason I'm no longer able to replicate this issue. I'll close this for now
