### ISSUE TITLE
Port stream resumption code for query streaming from Node.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/python-firestore#345]
Node code: https://github.com/googleapis/nodejs-firestore/blob/master/dev/src/reference.ts#L2125

Relevant Python Code: https://github.com/googleapis/python-firestore/blob/1d5c19a350bfb2337a3e3dfe520b1a464519433c/google/cloud/firestore_v1/query.py#L168

We should be able to mirror this node behavior in python. As we stream, we can save the last document. If we encounter an unexpected error, the original query could be resumed, with a startAfter clause, on behalf of the user.

see b/170400904 for further detail/discussion

**Comment by meredithslota** [comment]
We haven't seen significant demand for this, so closing this out. The internal issue linked above has additional context.
