### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by imesimone** [googleapis/python-firestore#349]
Hi,
I've just installed with pip3 this package (firebase_admin) on a Raspberry Pi Zero W (with the latest Rasbian w/o desktop environment). Everything is updated (even _apt update / upgrade_ has been tried). No missing dependency.

When I try to import firestore from firebase_admin (which imports the same package from google.cloud), Python 3.7 crashes and reports "Illegal instruction".
Nothing more and, obviously, it is not possible to understand what is the problem in depth since it is not caught by any try...except.

```
from google.cloud import firestore  # Illegal instruction
```

Have you ever experienced the same issue? Any ideas?

**Comment by tseaver** [comment]
@imesimone  How did you install the `google-cloud-firestore` library?  Can you please show the output from a `pip list` command in your environment?

**Comment by tseaver** [comment]
Closing due to lack of requested information.  Please feel free to reopen / follow-up if you can provide that information.

**Comment by afonsofonbraga** [comment]
@tseaver Hi, I have the same error, I installed it by using ```pip3 install firebase_admin```

**Comment by afonsofonbraga** [comment]
```
pip3 list
Package                  Version  
------------------------ ---------
asn1crypto               0.24.0   
CacheControl             0.12.12  
cachetools               5.3.0    
certifi                  2022.12.7
cffi                     1.15.1   
charset-normalizer       3.0.1    
cryptography             39.0.1   
entrypoints              0.3      
firebase-admin           6.1.0    
google-api-core          2.11.0   
google-api-python-client 2.79.0   
google-auth              2.16.1   
google-auth-httplib2     0.1.0    
google-cloud-core        2.3.2    
google-cloud-firestore   2.10.0   
google-cloud-storage     2.7.0    
google-crc32c            1.5.0    
google-resumable-media   2.4.1    
googleapis-common-protos 1.58.0   
grpcio                   1.52.0   
grpcio-status            1.52.0   
httplib2                 0.21.0   
idna                     3.4      
keyring                  17.1.1   
keyrings.alt             3.1.1    
msgpack                  1.0.4    
pip                      18.1     
proto-plus               1.22.2   
protobuf                 4.22.0   
pyasn1                   0.4.8    
pyasn1-modules           0.2.8    
pycparser                2.21     
pycrypto                 2.6.1    
PyGObject                3.30.4   
PyJWT                    2.6.0    
pyparsing                3.0.9    
pyxdg                    0.25     
requests                 2.28.2   
rsa                      4.9      
SecretStorage            2.3.1    
setuptools               40.8.0   
six                      1.12.0   
uritemplate              4.1.1    
urllib3                  1.26.14  
wheel                    0.32.3   
```

**Comment by tseaver** [comment]
@afonsofonbraga Thanks for following up with more information.  Unfortunately, I am no longer active in support of the `google-cloud-firestore` library.  I can see from recent activity in this repository that @Mariatta or @parthea might be able to follow up.
