### ISSUE TITLE
Fetching a document takes very long when it has a large map with a large index

### ISSUE THREAD

**Issue by Cvratingen** [googleapis/python-firestore#351]
We have a database where we store information for some IOT devices. 
Now our devices routinely send out a value every [5 or 60 or 300] seconds. I'm using a firestore (native mode) database to save these values.

I've got a program which aggregates the messages and updates all the documents every ~10 minutes with all messages received. 
The structure of the database is as following:

```
- sensors (collection)
    - sensor1 (document)
        -  sensor_readings (subcollection)
            - readings_10-05-2021 (document)
            - readings_11-05-2021 (document)
            - readings_12-05-2021 (document)
    - sensor2 
    - etc. 
```

The document "readings_10-05-2021" will have a map with the values
```
- readings_10-05-2021
      - values (map)
             - "00:00:01" : 120
             - "00:01:01" : 121
             - "00:02:01" : 122
             - etc.
```

I'm trying to retreive this document with:
```python
db.collection("sensors").document("sensor1").collection("sensor_readings").document("readings_10-05-2021").get()
```

When the map has only 1 value it takes about ~.19 seconds 
When the map has 1440 values it takes about ~1.5 seconds 
When the map has 19200 values it takes about ~400 seconds 

I've tested this with documents of the roughly same size in bytes to account for download speeds.

note: fetching this document with the large map on the google cloud terminal takes ~1 second.

As advised by @samtstern posting this here.

#### Environment details
Python 3.9.2
pip 21.1.1
google-cloud-firestore 2.1.1

**Comment by tseaver** [comment]
@Cvratingen Can you show the full output of `pip list` in your environment?  There have been recent changes to the Python `protobuf` package which might help with your issue.

**Comment by tseaver** [comment]
I can confirm what seems an abnormally long time to fetch the document, after only a relatively short interval (a few seconds?) to save it:

```python
>>> import time
>>> from google.cloud.firestore_v1 import Client
>>> client = Client()
>>> collection = client.collection("repro-351")
>>> document = collection.document("doc-id")
>>> data = {"a": {f"{x}": x for x in range(19200)}}
>>> document.set(data)
>>> before = time.time(); snapshot = document.get(); after = time.time()
>>> print(f"Time: {after - before} seconds")
Time: 193.5851743221283 seconds
>>> snapshot.to_dict() == data
True
```

**Comment by tseaver** [comment]
Hmm, `_helpers.decode_dict` could be playing a role in this issue, likely due to not stripping away the `proto-plus` wrappers.

**Comment by tseaver** [comment]
Running the same `document.get()` with the patch from PR #458:

```python
>>> import time
>>> from google.cloud.firestore_v1 import Client
>>> client = Client()
>>> collection = client.collection("repro-351")
>>> data = {"a": {f"{x}": x for x in range(19200)}}
>>> document = collection.document("doc-id")
>>> before = time.time(); snapshot = document.get(); after = time.time()
>>> print(f"Time: {after - before} seconds")
Time: 0.7956831455230713 seconds
>>> snapshot.to_dict() == data
True
```
