### ISSUE TITLE
All actions freeze python on GCE instance

### ISSUE THREAD

**Issue by Tohaker** [googleapis/python-firestore#358]
#### Environment details

  - OS type and version: Ubuntu 20.04.2 LTS
  - Python version: 3.8.5
  - pip version: pip 20.0.2
  - `google-cloud-firestore` version: 2.1.1

#### Steps to reproduce

  1. Deploy f1-micro GCE instance with the image `ubuntu-os-cloud/ubuntu-2004-lts` and all other options set to default
  2. `pip install google-cloud-firestore`
  3. Open python interpreter with `python` and run the script below

#### Code example

```python
from google.cloud import firestore
db = firestore.Client()
ref = db.collection('channels').document('1')
ref.get()
```

#### Stack trace
Firstly, the program never errors. It sits there for ages, until I stop it with `ctrl-C`. Then this trace is shown;

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/carto/carto/venv/lib/python3.8/site-packages/google/cloud/firestore_v1/document.py", line 400, in get
    response_iter = self._client._firestore_api.batch_get_documents(
  File "/home/carto/carto/venv/lib/python3.8/site-packages/google/cloud/firestore_v1/services/firestore/client.py", line 677, in batch_get_documents
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/home/carto/carto/venv/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/carto/carto/venv/lib/python3.8/site-packages/google/api_core/retry.py", line 285, in retry_wrapped_func
    return retry_target(
  File "/home/carto/carto/venv/lib/python3.8/site-packages/google/api_core/retry.py", line 219, in retry_target
    time.sleep(sleep)
KeyboardInterrupt
```

Since this instance would just be using the default Compute Engine Service Account, I can't see this being an authentication issue. This code works perfectly fine in GAE and GCF, but for some reason on a plain old linux server it won't run? I'm at my wits end here...

**Comment by Tohaker** [comment]
So I figured out the problem, which was my instance had no service account linked to it - however, I'd have hoped the library would warn me about it, instead of just freezing the application without any error message.

**Comment by craiglabenz** [comment]
Thanks for this report, @Tohaker. I've recreated this issue and, as we were all guessing, this comes down to a retry loop that spins forever. The ultimate reason for this is that missing service accounts are captured as an UNAVAILABLE error, which trips the retry mechanisms.

Below is a data dump of what I've found:

Ultimately, when [this line executes deep within gRPC](https://github.com/googleapis/python-api-core/blob/155da5e18cc2fdcfa57de6f956b7d078e79cd4b7/google/api_core/grpc_helpers.py#L154), `result` has a status code of UNAVAILABLE and an HTML body that contains helpful hints like:

```
>>> result.debug_error_string()
'{"created":"@1622590964.064418626","description":"Getting metadata from plugin failed with error: (\'Failed to retrieve http://metadata.google.
internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Status: 404 Respon
se:\\nb\\\'<!DOCTYPE html>\\\\n<html lang=en>\\\\n  <meta charset=utf-8>\\\\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, wi
dth=device-width">\\\\n  <title>Error 404 (Not Found)!!1</title>\\\\n  <style>\\\\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-
serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{backgroun
d:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-
decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{backg
round:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-r
esolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-
moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device
-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-
size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\\\\n  </style>\\\\n  <a href=//www.google.com/><span id=logo aria-label=Goog
le></span></a>\\\\n  <p><b>404.</b> <ins>That\\\\xe2\\\\x80\\\\x99s an error.</ins>\\\\n  <p>The requested URL <code>/computeMetadata/v1/instanc
e/service-accounts/default/?recursive=true</code> was not found on this server.  <ins>That\\\\xe2\\\\x80\\\\x99s all we know.</ins>\\\\n\\\'\', 
<google.auth.transport.requests._Response object at 0x7fd4aa5daee0>)","file":"src/core/lib/security/credentials/plugin/plugin_credentials.cc","f
ile_line":90,"grpc_status":14}'
```

There are some values in that error that could be string-matched to raise exceptions or emit `logger.warning()` messages indicating the missing service account, but string-matching is extremely scary.

More updates coming soon.

**Comment by craiglabenz** [comment]
The GRPC team has this on their backlog for upcoming quarters - hopefully we have progress before too long 🤞

**Comment by meredithslota** [comment]
@craiglabenz Do you remember where the gRPC issue lives? I'd like to cross-reference it here.

**Comment by meredithslota** [comment]
Internal issue b/178107836 is marked as "In Progress".

**Comment by meredithslota** [comment]
Actually, that bug also addresses some internal issues — the relevant fix here has (I think) been merged here: https://github.com/grpc/grpc-java/pull/9102 (https://github.com/grpc/grpc-java/pull/9118 was the revert earlier). I think this is ok to close out but @Tohaker if you see this again, can you please file a new issue?

**Comment by meredithslota** [comment]
Whoops, linked the wrong issue (that one is for grpc-java).

**Comment by meredithslota** [comment]
We believe this is fixed, and I haven't seen a comment from impacted users since 2021 — if folks are still encountering issues, can you please open a new issue with updated repro steps? Thanks!
