### ISSUE TITLE
Typing documents?

### ISSUE THREAD

**Issue by louis030195** [googleapis/python-firestore#364]
**Is your feature request related to a problem? Please describe.**

In TypeScript and [Flutter Firestore SDK](https://firebase.flutter.dev/docs/firestore/usage/#typing-collectionreference-and-documentreference) you read/write typed documents, it is much more maintainable IMHO, I wonder if something similar would be possible on the Python SDK?

I am kind of new to Python typing, so I hope what I propose is actually possible? Otherwise, I would gladly learn something from my mistake.

 **Describe the solution you'd like**

```python
import os
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

class Foo:
    def __init__(self):
        self.bar = "baz"
 
cred = credentials.Certificate(os.environ["GOOGLE_APPLICATION_CREDENTIALS"])
firebase_admin.initialize_app(cred)
firestore_client: BaseClient = firestore.client()
foos_ref: BaseCollectionReference = firestore_client.collection(u"foos")

for foo in foos_ref.stream().with_converter(Foo):
    print(foo.bar)
    
```

 **Describe alternatives you've considered**

No type

**Comment by meredithslota** [comment]
Closing in favor of #447 as these are related. Thanks!
