### ISSUE TITLE
Change Type Hit at AsyncCollectionReference.document

### ISSUE THREAD

**Issue by sizumita** [googleapis/python-firestore#369]
**Is your feature request related to a problem? Please describe.**

Return Type Hint at AsyncCollectionReference.document is always DocumentReference, but actually AsyncDocumentReference.
My Editor(Jetbrains IDE) tells me that AsyncDocumentReference is wrong Type.
<img width="681" alt="スクリーンショット 2021-06-15 17 54 31" src="https://user-images.githubusercontent.com/17804838/122023692-be20a900-ce02-11eb-8e56-7cafe67019ac.png">

 **Describe the solution you'd like**

I think to change Return Type Hint is the best solution:

```python
def document(self, document_id: str = None) -> AsyncDocumentReference:
    """..."""
    return super().document(document_id)
```

 **Describe alternatives you've considered**

I think this solution can change Return Type Hint simply.

 **Additional context**

Nothing.

**Comment by craiglabenz** [comment]
This is a good suggestion, @sizumita. I'll try to get to this soon :)

**Comment by sizumita** [comment]
thanks!
