### ISSUE TITLE
Bundles incorrectly calculating length prefix

### ISSUE THREAD

**Issue by craiglabenz** [googleapis/python-firestore#390]
[On this line](https://github.com/googleapis/python-firestore/blob/c54de50922b810cac030a71526bf62b9e4785a2f/google/cloud/firestore_bundle/bundle.py#L346), the bundle should be returning the length of the utf-8 encoded serialized JSON string; not just the length of the string itself.

Searching for a test case that fails in the current implementation.

**Comment by craiglabenz** [comment]
In regards to the search for a failing test, the following code executes without error (and these were the edge cases that were on my radar to check):

```py
import json

def raw_length(data: str) -> int:
    return len(json.dumps(data))

def bytes_length(data: str) -> int:
    return len(json.dumps(data).encode("utf-8"))

# Simple
data = {'a': True}
assert raw_length(data) == bytes_length(data)

# Special character
data = {'a': '√'}
assert raw_length(data) == bytes_length(data)

# Compound emoji
data = {'a': '🧜🏿‍♀️'}
assert raw_length(data) == bytes_length(data)
```

**Comment by wu-hui** [comment]
With Python3

```
>>> ibrow = "🤨"
>>> len(ibrow)
1
>>> ibrow.encode("utf-8")
b'\xf0\x9f\xa4\xa8'
>>> len(ibrow.encode("utf-8"))
4
```

Taken from https://realpython.com/python-encodings-guide/

**Comment by craiglabenz** [comment]
Ah yes, that's definitely a thing, but `json.dumps` handles this encoding.

```
>>> import json

>>> ibrow = "🤨"
>>> json.dumps({'ibrow': ibrow})
>>> serialized
'{"ibrow": "\\ud83e\\udd28"}'
>>> len(serialized)
25
>>> len(serialized.encode("utf-8"))
25
```

I think we can close this ticket.
