### ISSUE TITLE
Docs-presubmit failing on python-firestore

### ISSUE THREAD

**Issue by dandhlee** [googleapis/python-firestore#408]
Firestore seem to be one of the rare ones that got swept up in a mishandling of xrefs from the docs generated. It looks fixed and will be fixed with a new `gcp-sphinx-docfx-yaml` release after https://github.com/googleapis/sphinx-docfx-yaml/pull/90 is merged.

For now, if possible please ignore docs-presubmit if it shows up the following error:
```
sphinx.errors.ExtensionError: Handler <function process_docstring at 0x7f61685de940> for event 'autodoc-process-docstring' threw an exception (exception: 'NoneType' object has no attribute 'groupdict')
```

**Comment by tseaver** [comment]
The `docfx` build has been failing routinely, including on `main`, for quite a while (since at least 2021-08-26).
