### ISSUE TITLE
using field_path to add '#' (hashtag) in field name creates 2 different fields on set and update operations

### ISSUE THREAD

**Issue by 1337SEnergy** [googleapis/python-firestore#443]
#### Environment details

  - OS type and version: Windows 10 19042.1165
  - Python version: 3.8.6
  - pip version: 21.2.4
  - `google-cloud-firestore` version: 2.3.1

#### Steps to reproduce

  1. have non-existing document
  2. call set() function on a document with a key obtained by field_path that contains a hashtag (this will create a backticked field)
  3. call update() function with the same key (this will create a field with normal name)
  4. end result will look like this: 
![image](https://user-images.githubusercontent.com/18123409/132058531-dc787119-3352-407a-a2bf-95ae0ee3a93b.png)

calling update again will increment the non-backticked field

according to https://stackoverflow.com/questions/51962572/firestore-document-field-names-with-spaces-return-an-error-when-used-with-where/52046074#52046074 and https://stackoverflow.com/questions/53939273/start-getting-error-non-alphanum-char-in-element-with-leading-alpha-error-wh I should use the field_path to make a field with name that contains non-alphanumerical characters

#### Code example

```python
  username = self.db.field_path(f"{user.name}#{user.discriminator}")
  
  if not self.heart_doc_ref.get().exists:
    self.heart_doc_ref.set({username:1})
  else:
    self.heart_doc_ref.update({username:firestore.Increment(1)})
```

**Comment by tseaver** [comment]
@1337SEnergy  The semantics you are expecting when using a field path are only supported for `Document.update` (see its [docs](https://googleapis.dev/python/firestore/latest/document.html#google.cloud.firestore_v1.document.DocumentReference.update)), and not for `Document.set` (see its [docs](https://googleapis.dev/python/firestore/latest/document.html#google.cloud.firestore_v1.document.DocumentReference.set)).

For your example, you don't want a field path until the `update` call:
```python
username = f"{user.name}#{user.discriminator}"
if not self.heart_doc_ref.get().exists:
    self.heart_doc_ref.set({username: 1})
else:
    username_path = self.db.field_path(username)
    self.heart_doc_ref.update({username_path: firestore.Increment(1)})
```
