### ISSUE TITLE
`google.cloud.firestore` lacks packaged typing

### ISSUE THREAD

**Issue by nipunn1313** [googleapis/python-firestore#447]
Hi.
`google.cloud.firestore` does not have types via [PEP561](https://www.python.org/dev/peps/pep-0561/)
`google.cloud.firestore_v1` and friends do.

Per the PEP:
```
This PEP does not support distributing typing information as part of module-only distributions. The code should be refactored into a package-based distribution and indicate that the package supports typing as described above.
```

You'll have to refactor `firestore.py` into a directory structure
```
google/
  cloud/
    firestore/
      __init__.py
      py.typed 
```

Repro steps:

```python
# ~/test/test.py
# firestore doesn't have py.typed yet - only firestore_v1 has
from google.cloud.firestore import AsyncClient
from google.cloud.firestore_v1 import AsyncClient
```

```
python3 -m venv venv
source venv/bin/activate
pip install google-cloud-firestore
# or `pip install -e ~/src/python-firestore` for a local checkout
mypy --python-executable=venv/bin/python test.py
```

**Comment by tseaver** [comment]
`google.cloud.firestore` is just a backward-compatibility shim: it doesn't define any types at all, except for the (spurious, to me) typing of `__all__` as `List[str]` -- who needs typing for a literal?

If that `List[str]` is causing actual, rather than theoretical breakage, I'd rather just remove it.

**Comment by nipunn1313** [comment]
Hiya - thanks for looking
The contents of `firestore.py` aren't causing any issues - it's all totally fine.

Take a look at #448 which would fix this by renaming `firestore.py` to `firestore/__init__.py` and adding a `py.typed`. The runtime behavior will be fully equivalent (shim will still work).

It's just that according to PEP561, typing information is not distributed to module-only distributions (eg `firestore.py`). It is only distributed via package distribution (eg `firestore/__init__.py` and `firestore/py.typed`). `google.cloud.firestore_v1` obeys PEP561 for example.

Type checkers (mypy / pyright) will not currently locate types for `google.cloud.firestore` - because mypy/pyright obey PEP561. For example
```python
from google.cloud.firestore import AsyncClient
reveal_type(AsyncClient)  # will reveal as `Any` until #448 lands.
```

**Comment by tseaver** [comment]
@nipunn1313 `firestore.py` is *not* a "module-only distribution"  -- it is a module within the *namespace package* `google-cloud`, bundled as part of the `google-cloud-firestore` distribution, which is decidedly a "package distribution."

Because `firestore.py has no meaningful typing of its own, it doesn't need a `py.typed` file -- if it *did* require one, it could be along-side `firestore.py` in the namespace package.

**Comment by nipunn1313** [comment]
Thanks for the clarification!

> Because firestore.py has no meaningful typing of its own, it doesn't need a py.typed file

`firestore.py` does reexports - which I believe type checkers (mypy/pyright) consider to be meaningful types. Without a `py.typed` - the typecheckers aren't even going to look in there to understand that the reexports exist. I did a quick test and confirmed this w/ both mypy and pyright.

```python
from google.cloud.firestore import AsyncClient as AC1
from google.cloud.firestore_v1 import AsyncClient as AC2
reveal_type(AC1)
reveal_type(AC2)
```
mypy:
```
test.py:2: error: Skipping analyzing "google.cloud.firestore": found module but no type hints or library stubs
test.py:2: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
test.py:5: note: Revealed type is "Any"
test.py:6: note: Revealed type is "def (project: Any =, credentials: Any =, database: Any =, client_info: Any =, client_options: Any =) -> google.cloud.firestore_v1.async_client.AsyncClient"
Found 1 error in 1 file (checked 1 source file)
```
pyright
```
Found 1 source file
/Users/nipunn/src/pyright_google_repro/test.py
  /Users/nipunn/src/pyright_google_repro/test.py:5:13 - info: Type of "AC1" is "Unknown"
  /Users/nipunn/src/pyright_google_repro/test.py:6:13 - info: Type of "AC2" is "Type[AsyncClient]"
```



I think there might be some ambiguity in the terminology and spec of PEP561 here - particularly around requirements for modules within namespace packages. I'm in the process of trying to clarify this https://github.com/python/peps/pull/2083, so any feedback appreciated. See this comment https://github.com/microsoft/pyright/issues/2113#issuecomment-921304097 for some of the intention

typecheckers rely on a `py.typed` file inside the module directory to consider the package inline typed (eg `google/cloud/firestore_v1/py.typed`). PEP 561 expressly forbids having `py.typed` in the namespace package - for good reason, because the namespace package (`google/cloud` in this case) is shared across multiple distributions.

I don't think the PEP explains how to indicate types for something like `google/cloud/firestore.py`. It says:
```
For namespace packages (see PEP 420), the py.typed file should be in the submodules of the namespace, to avoid conflicts and for clarity.

This PEP does not support distributing typing information as part of module-only distributions. The code should be refactored into a package-based distribution and indicate that the package supports typing as described above.
```
My inference here - is that it's encouraging `google/cloud/firestore.py` to be inlined typed by factoring into `google/cloud/firestore/__init__.py` with `google/cloud/firestore/py.typed`.

**Comment by nipunn1313** [comment]
I would note that the example usage in your README won't get types since it does `from google.cloud import firestore`
