### ISSUE TITLE
Please cut a new release

### ISSUE THREAD

**Issue by PaulMcMillan** [googleapis/python-firestore#50]
I am using version 1.6.2, and lost quite a while to debugging why the issue fixed in this commit was causing my code to fail:
https://github.com/googleapis/python-firestore/commit/de3aca0e78b68f66eb76bc679c6e95b0746ad590

Until that's fixed, transactions are much more clumsy to work with than intended.

**Comment by crwilcox** [comment]
Fixed in #41
