### ISSUE TITLE
Questions about Target ID in firestore.Watch

### ISSUE THREAD

**Issue by billyrrr** [googleapis/python-firestore#51]
Hi, 

I was wondering if there are reserved target IDs are for Firestore Python Client or Firestore RPC protobuf. I plan to use Target ID and resume token to build a load balancing service registry that modifies the target/ListenRequest in each of the worker instances to be able to scale up the number of workers listening to the same target. To achieve this, I hope to know if particular values of Target ID may collide or interfere with the functioning of the Python client library or protobuf. For now, I read that the Target ID in separate ListenRequest in RPC seem to be independent, but I was wondering if there is any exception to this rule. For example, there seem to be one Target ID assigned for python: ```WATCH_TARGET_ID = 0x5079  # "Py"```. Should I avoid this or any other Target IDs? Also, do I start a new Stream every time a ```ListenRequest``` is constructed? And can a new server pick up a ResumeToken if target matches the target on the current server generating the ResumeToken? 

Any help is appreciated. I could not find much documentations except references like the one in this [link](https://google-cloud-python.readthedocs.io/en/0.32.0/firestore/types.html). 

Thanks!

**Comment by crwilcox** [comment]
Hi @billyrrr there are a few quesitons in here I think. Let me know if I missed any or you need more information

There are different target ids for each language client. We do not have a published list, but they are all basically the hex equivalent of the language. for instance "Go" for golang. 

If you have a resume token that request should be resumable on another channel/machine.

As for avoiding the target ids, I am unsure if that is really necessary? Though it does seem a good practice to have a unique one for your purpose, just as a way of differentiating if just in your own logging/debugging.

**Comment by billyrrr** [comment]
Thank you for the detailed answer, @crwilcox . I had a few other questions. Does a ListenStream support listening to multiple target_id's? Or what is the best practice for the number of target_id's in a ListenStream? Is the read timestamp on all documents returned monotonically non-decreasing for all ListenResponse sent back in a ListenStream? (or are they monotonically non-decreasing within the same Target/ListenRequest?) 

Thank you!

**Comment by crwilcox** [comment]
> 1. Does a ListenStream support listening to multiple target_id's? Or what is the best practice for the number of target_id's in a ListenStream?

A watch (listen stream) is created with a query, collection, document. So you will likely have a separate stream per watch type.

> 2. Is the read timestamp on all documents returned monotonically non-decreasing for all ListenResponse sent back in a ListenStream? (or are they monotonically non-decreasing within the same Target/ListenRequest?)

Ordering for watch should use the same semantics of a query at that point in time. As firestore has concepts of ordering I can't say for sure that the timestamp is the order.

> 3. Also, if a document is updated across multiple target_id's, will the change be sent for every target_id's or around one change that references multiple target_ids?

The change will be sent for whatever targets it has changed. If you watch document `a/b/c` and also collection `a/b`, both will received an update if you alter `a/b/c`

> 4. Will a Document (Doc_1) be sent again for a newly added target (Target_2) if Target_1 contains Doc_1 and has sent TargetChange.CURRENT?
> 
> > Target_1: watches Doc_1, Doc_2
> > Target_2: watches Doc_1, Doc_3
> 

I am unsure about this one, though I think the answer is no. 


> 1. Will a read be charged at least as many times that a document is referenced by a target_id, or there are other limitations?

What do you mean by 'will a read be charged'. Do you mean in the billing sense of charges?

**Comment by craiglabenz** [comment]
Closing this issue for now, but feel free to re-open if any further questions arise.
