### ISSUE TITLE
Cannot update data - GRPC Stream Removed

### ISSUE THREAD

**Issue by hminle** [googleapis/python-firestore#528]
Hi,

I just want to perform update data to firestore. But got the issue about GRPC.
Could you guys please help?

#### Environment details

  - OS type and version: Fedora 33
  - Python version: 3.8
  - pip version: 21.3.1
  - `google-cloud-firestore` version: 2.3.4

#### Code example

```python
        app = firebase_admin.get_app(name="gma")
        db = firestore.client(app)

        data = {
            unidecode(method_name): {
                u"rmse": round(rmse, 6),
                u"psnr": round(psnr, 2),
                u"rmse_oog": round(rmse_oog, 6), 
                u"psnr_oog": round(psnr_oog, 2), 
                u"training_time": round(training_time, 2),
            }
        }

        print(data)
        retry = google.api_core.retry.Retry()
        db = self._get_db_pointer()
        db.collection(self.table_name) \
        .document(unidecode(image_filename)) \
        .update(data, retry=retry)
```

#### Stack trace
![image](https://user-images.githubusercontent.com/16201681/151810771-a0d15620-231a-4f37-8d66-6551c49ae345.png)
![image](https://user-images.githubusercontent.com/16201681/151810806-f22b5b43-bdcd-4598-ba8e-670762070189.png)

Thanks!

**Comment by meredithslota** [comment]
Hi there — there have been a number of fixes released since this issue was filed, including one that might be related to the `stream removed` issue. Can you please check with an updated library version if this issue is persisting?

**Comment by Mariatta** [comment]
We haven't heard back after a year. Closing. Please re-open if you have new information using newer version of the library.
