### ISSUE TITLE
Pylance is not satisfied with the typings

### ISSUE THREAD

**Issue by NixBiks** [googleapis/python-firestore#570]
I'm using VSCode with pylance (as I think most python developers do).

If I use the async example from the docs then I'm getting a type error

```
Argument of type "Literal[_MethodDefault._DEFAULT_VALUE]" cannot be assigned to parameter "retry" of type "Retry" in function "get"
  "Literal[_MethodDefault._DEFAULT_VALUE]" is incompatible with "Retry" Pylance(reportGeneralTypeIssues)
```

#### Environment details

  - OS type and version: macOS 12.3.1
  - Python version: 3.9.9
  - pip version: 22.04
  - `google-cloud-firestore` version: 2.4.0

#### Steps to reproduce

Create example from docs

```python
from google.cloud import firestore


async def abc():
    db = firestore.AsyncClient()
    doc_ref = db.collection("cities").document("SF")

    doc = await doc_ref.get()
    if doc.exists:
        print(f"Document data: {doc.to_dict()}")
    else:
        print("No such document!")
```

Let me know if you need more information

<img width="566" alt="Screenshot 2022-04-23 at 15 59 02" src="https://user-images.githubusercontent.com/16841792/164909135-b9f6d96a-dfa6-40bd-b4b3-1d7966af4563.png">

**Comment by mr-bjerre** [comment]
So I guess it's because it expects `Retry` class as argument but `_MethodDefault._DEFAULT_VALUE` is given which is just equal to `object()`. Would it be possible to simply have `_MethodDefault._DEFAULT_VALUE = Retry()` instead? or expect `Retry | object` in the args (same goes for `update`, `delete`, `set` etc.)

**Comment by casparolesen** [comment]
We're having the same problem here. Sucks to have to ignore a bunch of lines.

**Comment by meredithslota** [comment]
Agreed — we need to overhaul our typing here, and I'm consolidating related issues (you aren't alone in this complain) into one: #447 Thanks for filing this, and thanks for your patience.
