### ISSUE TITLE
WriteResult returns transformation results out of order

### ISSUE THREAD

**Issue by guneemwelloeux** [googleapis/python-firestore#671]
google-cloud-firestore==2.7.3
Python 3.9.13

Considering the following example:
```
>>> d = ref.update({"time": Maximum(1), "utc": Maximum(4), "server": SERVER_TIMESTAMP})
>>> d
update_time {
  seconds: 1671461480
  nanos: 971679000
}
transform_results {
  timestamp_value {
    seconds: 1671461480
    nanos: 936000000
  }
}
transform_results {
  integer_value: 1
}
transform_results {
  integer_value: 4
}
```

The transform results are returned in a different order than what was specified in the `update` call.
In Python3, dictionaries retain the order in which they were created, so I would expect the transform results to be in the same order as the fields provided in the `update`.

The official doc for the WriteResult RPC message indicates that the order should be the same: https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1#writeresult

**Comment by Pran-Ker** [comment]
Firestore is a distributed system, and the order in which the updates are applied may not be deterministic. Additionally, the Firestore API may choose to optimize the order in which the updates are applied to reduce latency or improve throughput. Instead, you should access the results by their field names, as in the following example:

```
update_dict = {"time": Maximum(1), "utc": Maximum(4), "server": SERVER_TIMESTAMP}
update_ref = ref.update(update_dict)

# Access the transform results by field name
time_transform = update_ref.transform_results["time"]
utc_transform = update_ref.transform_results["utc"]
server_transform = update_ref.transform_results["server"]

```

**Comment by guneemwelloeux** [comment]
The above code snippet is not working with the version I'm using.
Here is the error I'm getting:
```
>>> from google.cloud.firestore import Increment
>>> res = doc.reference.update({"new": Increment(1)})
>>> res.transform_results
[integer_value: 2
]
>>> res.transform_results['new']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/.../.pyenv/versions/editor/lib/python3.9/site-packages/proto/marshal/collections/repeated.py", line 125, in __getitem__
    return self._marshal.to_python(self._pb_type, self.pb[key])
  File "/Users/.../.pyenv/versions/editor/lib/python3.9/site-packages/google/protobuf/internal/containers.py", line 93, in __getitem__
    return self._values[key]
TypeError: list indices must be integers or slices, not str
```

Could you please let me know in which version this was added?

Thanks
