### ISSUE TITLE
Firestore: extremely slow reads and writes

### ISSUE THREAD

**Issue by kanyesthaker** [googleapis/python-firestore#7]
**Environment Details**
1. Firestore
2. Mac OS Catalina v 10.15.1
3. Python 3.7.1
4. google-cloud-firestore 1.6.1

I'm testing simple database reads and writes on a **very** simple Firestore database. I'm looking at a single document within a single collection with 1 field; however, when I try to write (as shown below), the timer I have (also in the below code) shows that the first write takes **over 30 seconds**. This same behavior is present for reads. 

However, this is only present for the first write/read in this python script. All subsequent writes/reads are timed at roughly 100ms (still slow for such a tiny database). I have not been able to find this issue replicated on the internet, and there is no mention of behavior like this in the Firestore Python SDK documentation. I am running the below code locally on my machine.

**Steps to Reproduce**
Shown below

**Code Example**
```
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore
import datetime

cred = credentials.Certificate("./path/to/adminsdk.json")
firebase_admin.initialize_app(cred)
db = firestore.client()

start = datetime.datetime.now()

#takes roughly 30.3 seconds
doc_ref = db.collection(u'test_collection').document(u'test_document')
doc_ref.set({u'test_field':'data'})

time_after_first = datetime.datetime.now()
print(time_after_first - start)

#takes roughly 80 ms
doc_data = doc_ref.get()
print(doc_data).get('test_field')

print(datetime.datetime.now()-time_after_first)

print("done")
```

Any explanation for this behavior? Thank you!

**Comment by BenWhitehead** [comment]
Hi @kanyesthaker,

My best guess based on the code sample is that there is some latency in the token being able to be acquired before the request is able to succeed. However the code sample you have attached I believe is actually for the https://github.com/firebase/firebase-admin-python library, not this one.

You will likely reach folks more familiar with the credential loading and client initialization if you re-open this issue over in the https://github.com/firebase/firebase-admin-python repo.

**Comment by pinkyxw** [comment]
same issue here, it happens to me sometimes only

**Comment by LeonardoRick** [comment]
Hi, I got the same problem here. What's weird is that it was not happening before and suddenly it stated to take **3 minutes** to make the first call sometimes!

this is my log

```
firebaseConfig: 0:00:00.000476
user doc ( simply userRef.get().to_dict() ): 0:03:00.657157
another doc: 0:00:00.531594
```

On my case, as @kanyesthaker, it happens only on first call too. Any updates or guesses on this issue?

**Comment by sudonims** [comment]
same for me,  db read/ write takes around 30 - 40 seconds to complete and token verification taking about 10-12 minutes... The problem started today out of the blue....


127.0.0.1 - - [10/Sep/2020 00:34:51] "OPTIONS /getworkspace/123_retrain HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2020 00:34:51] "OPTIONS /getworkspace/all HTTP/1.1" 200 -
trying before_request
trying before_request

entered the route
127.0.0.1 - - [10/Sep/2020 00:45:53] "GET /getworkspace/123_retrain HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2020 00:45:53] "GET /getworkspace/all HTTP/1.1" 200 -


If you look the timestamp..it is nearly 12 minutes

**Comment by sudonims** [comment]
Solved the problem. I uninstalled all the google related pip packages (gcloud, firebase-admin, everything). Reinstalled them...upgraded requests lib(for urllib3 "status" err)...upgraded "six" package to 1.15.0 and it worked. My guess is problem is related to some cache generated...

**Comment by jeroenVerdonschot** [comment]
I still have this problem. Running on cloud functions. A simple read of a very small document could take up to 5 min. I deleted my rules and it took 4 secs. Still very slow for only getting data (no querries).

Does anyone know how to clear my cache?

**Comment by craiglabenz** [comment]
Closing this since updating dependencies seems to have solved the issue. If anyone sees this behavior again from `google.cloud import firestore`, please re-open with a full stack trace.
