### ISSUE TITLE
Using "%" or ":" in firestore emulator document Id's

### ISSUE THREAD

**Issue by sameerahmed56** [googleapis/python-firestore#711]
Hey guys,
Facing issues using Firebase emulator UI when naming the document IDs with characters `%` or `:`. These characters are allowed in the document ID names as mentioned in the documentation. [Docs: documents naming limit](https://firebase.google.com/docs/firestore/quotas#:~:text=Collections%2C%20documents%2C%20and%20fields,-Limit&text=A%20simple%20field%20name%20is,9%20%2C%20and%20underscore%20(%20_%20))
Naming the document IDs with `%` or `:` works perfectly fine in firestore database on google cloud platforms.

1. Using `%` in any document will not even allow the document to open in the emulator UI. You will also get an error page when the document is created with `%` in the document ID.
2. Using `:` in any document will not show sub-collections in the emulator UI. You can still see the document inside sub-collections if you write the whole path of documents.

#### Environment details

  - OS type and version: `Ubuntu 20.04`
  - Python version: `3.10.11`
  - pip version: `23.0.1`
  - node version: `v18.12.1`
  - google-cloud-firestore : `2.11.0`

#### Steps to reproduce

  1. Running the Firebase emulator.
  2. Create a document with the character `%` or `:` in the emulator.
  4. Create a sub-collection inside those documents.
  5. Create documents inside with any name inside those sub-collections.

Attaching screenshots when using `:` in the document ID.

![Screenshot from 2023-05-05 13-44-19](https://user-images.githubusercontent.com/54800755/236412274-b8818732-a517-44ca-886b-a3c731371a15.png)
![Screenshot from 2023-05-05 13-46-16](https://user-images.githubusercontent.com/54800755/236412340-7039a583-374c-4399-b67e-87392d933928.png)

Thanks

**Comment by meredithslota** [comment]
Thanks for filing this issue! This repo is for the Python client library, and this doesn't appear to be related to the Python client specifically, but the emulator — am I understanding that correctly? I think this issue has been previously reported here: https://github.com/firebase/firebase-tools-ui/issues/665 (Googlers, internal issue is filed here: b/208894885). I'm going to close this out in favor of that one.
