### ISSUE TITLE
Request to clarify docs as to whether AsyncClient allows concurrent access

### ISSUE THREAD

**Issue by dfb** [googleapis/python-firestore#745]
Does AsyncClient support concurrent access by multiple coroutines, or is some sort of guard needed for parallel tasks?

I am using the firebase admin SDK and the Firestore `google.cloud.firestore_v1.async_client.AsyncClient` to process documents from a collection. I have multiple processor coroutines that run in "parallel" (I/O bound) and I'm wondering if I can safely give them a reference to the same AsyncClient instance and let them retrieve/update documents as needed, or if I should e.g. set up a client pool and have them borrow a client from the pool as needed.

I've tried just letting them access the same client and it seems to work, but it's a small test and so I'd like confirmation that this type of usage is expected to work. I checked [the documentation](https://cloud.google.com/python/docs/reference/firestore/latest) and the Issues list for this project but couldn't find the answer - apologies if it's there and I just missed it.

I'm using Python 3.11.4 and:
```
firebase-admin==6.2.0
google-cloud-core==2.3.3
google-cloud-firestore==2.11.1
```

**Comment by daniel-sanche** [comment]
Sorry, I realize this is an old bug, but you should be able to share the same instance across multiple coroutines without issue.  I'd refer you to the [`asyncio` documentation](https://docs.python.org/3/library/asyncio.html) for concurrency best practices, but as long as you aren't mixing multiple methods of concurrency, you should be safe

Feel free to share code snippets in case I'm misunderstanding the question, and I can give more specific advice

**Comment by daniel-sanche** [comment]
Since this is an old question, I'm going to mark it as closed, but feel free to re-open if you still have questions
