### ISSUE TITLE
Issue while attempting to deploy Firebase functions.

### ISSUE THREAD

**Issue by nikhilkotiya** [googleapis/python-firestore#752]
Hello everyone,

I am writing this email to address some challenges we've encountered while attempting to deploy Firebase functions. Currently, when we deploy a single function using the command "firebase deploy --only functions:function_name," the deployment process works smoothly and the function is correctly deployed. However, when we utilize the command "firebase deploy --only functions" to deploy all functions, we're encountering an issue where all the functions end up with the same container image URL. As a result, this is causing requests to be directed to only one function instead of the intended target functions.

Thank you.

**Comment by daniel-sanche** [comment]
Hey Nikhil, unfortunately this repo is specifically for the client library for [Firestore](https://firebase.google.com/docs/firestore), the database service. You might be able to get help by posting this issue in the [firebase-functions repository](https://github.com/firebase/firebase-functions), or reaching out to [Firebase support ](https://firebase.google.com/support) directly

Thanks
