### ISSUE TITLE
Please support delete_database

### ISSUE THREAD

**Issue by NickChittle** [googleapis/python-firestore#760]
It looks like we support creating a database [programatically](https://github.com/googleapis/python-firestore/blob/b8cbf1d32414933f82174a4778d641324c8f1de9/google/cloud/firestore_admin_v1/services/firestore_admin/client.py#L1622) but don't support deleting a database.

**Comment by daniel-sanche** [comment]
We discussed this offline, and found that delete_database is currently in preview, and will be added when it reaches GA
