### ISSUE TITLE
transactions that aren't retried don't rollback

### ISSUE THREAD

**Issue by daniel-sanche** [googleapis/python-firestore#765]
in [Transaction.__call__](https://github.com/googleapis/python-firestore/blob/9840d4345dca49ba610ae8e3ce4955678c18c49c/google/cloud/firestore_v1/transaction.py#L280), rollback is called [when retries are exhausted](https://github.com/googleapis/python-firestore/blob/9840d4345dca49ba610ae8e3ce4955678c18c49c/google/cloud/firestore_v1/transaction.py#L313), or [when pre-commit fails](https://github.com/googleapis/python-firestore/blob/9840d4345dca49ba610ae8e3ce4955678c18c49c/google/cloud/firestore_v1/transaction.py#L249), but other exceptions cause an [immediate raise](https://github.com/googleapis/python-firestore/blob/9840d4345dca49ba610ae8e3ce4955678c18c49c/google/cloud/firestore_v1/transaction.py#L278), without any rollback.

To fix this, the entire `__call__` function should be wrapped in a `try...except` block, that causes a rollback before any exceptions are raised out of the transaction

**Comment by kolea2** [comment]
It looks like this was fixed in https://github.com/googleapis/python-firestore/pull/767, closing. @daniel-sanche please reopen if needed. Thanks!
