### ISSUE TITLE
Typing lack of precision: bad return type for BaseQuery.get()

### ISSUE THREAD

**Issue by XGeffrier** [googleapis/python-firestore#784]
Hi Python Firestore team!

The `BaseQuery` class has a `get()` method, and the defined typing specifies ([here](https://github.com/googleapis/python-firestore/blob/main/google/cloud/firestore_v1/base_query.py#L978C10-L978C18)) it should return an `Iterable`  of `DocumentSnapshot`. However, it returns a list, (which is perfectly fine, since `stream()` has a behavior similar to `get()` and returns an iterator).

I know, I know, lists are technically Iterable, but some list-specific methods, applied on query answers, will trigger inspection warnings since we can't ensure it is a list. 

#### Code example

```python
db: "Client" = firestore.client()
collec = db.collection("mycollection")
docs = collec.where(filter=FieldFilter("someField", "==", "someValue")).get()

docs_nb = len(docs)
# this last line works, but will trigger an inspection warning,
# as all Iterables don't support len() (but lists do)
```

Maybe not the first world problem, but could we change the typing so inspections or IDEs understand it is a list? Or are there some cases where it is not one?

**Comment by daniel-sanche** [comment]
Thanks for reporting this. It's currently a known issue that the [type hints in this library are broken](https://github.com/googleapis/python-firestore/issues/773). There's a good chance we will have to resolve it by [stripping them all out](https://github.com/googleapis/python-firestore/pull/823), and adding them back over time

I'd suggest using `typing.cast` in the meantime if you want to override the hints exported by the library

**Comment by daniel-sanche** [comment]
update: we are working on a couple new features, but this and other type hint fixes are a high priority item once those are in

**Comment by daniel-sanche** [comment]
fixed in https://github.com/googleapis/python-firestore/pull/984
