### ISSUE TITLE
Firestore: Cannot get Quickstart to work

### ISSUE THREAD

**Issue by sandroboehme** [googleapis/python-firestore#794]
I followed the [quickstart guide][1] for Firestore in Python but I couldn't get it to run as I got this error message:

```
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Name resolution failure"
	debug_error_string = "{"created":"@1554833859.769886000","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2267,"referenced_errors":[{"created":"@1554833859.769576000","description":"Name resolution failure","file":"src/core/ext/filters/client_channel/request_routing.cc","file_line":165,"grpc_status":14}]}"
...
google.api_core.exceptions.ServiceUnavailable: 503 Name resolution failure
```

This is my code:
```
db = firestore.Client()
doc_ref = db.collection(u'users').document(u'alovelace')
doc_ref.set({
    u'first': u'Ada',
    u'last': u'Lovelace',
    u'born': 1815
})

# Then query for documents
users_ref = db.collection(u'users')
docs = users_ref.get()

for doc in docs:
    print(u'{} => {}'.format(doc.id, doc.to_dict()))
```

 1. The data is there: [![the viewer][2]][2]
 2. The environment on Mac is set like this:
`export GOOGLE_APPLICATION_CREDENTIALS=/path/to/credentials.json` for  authentication
 3. `google-cloud-firestore` is installed in a new virtualenv as described in the quickstart guide.
 4. I made sure that I'm using the right `gcloud` project with:
`gcloud config set project example4`
 5. `python --version` returns `Python 3.7.1`
 6. My [Stackoverflow question](https://stackoverflow.com/questions/55563432/cannot-get-firestore-quickstart-to-work-in-python) didn't got a response. But I'm happy to mark an answer as working there if I can!

There must me something simple missing. Any hints are appreciated!

  [1]: https://cloud.google.com/firestore/docs/quickstart-servers?authuser=2
  [2]: https://i.stack.imgur.com/9OQWH.png

**Comment by 00cyre** [comment]
solved it by not using firestore, and using realtime db instead xD

**Comment by daniel-sanche** [comment]
Closing as this is an old issue, which I don't believe is currently impacting anyone. If anyone is still seeing this issue, let me know and I'll try to reproduce
