### ISSUE TITLE
feat: Support for `async` - `on_snapshot` callback

### ISSUE THREAD

**Issue by y3rbiadit0** [googleapis/python-firestore#836]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
I wanted to run async callbacks when a new change in a given collection was occurring.

 **Describe the solution you'd like**
The solution I propose is to support async functions as callbacks as well, using asyncio, so developer using this won't notice the difference.

 **Describe alternatives you've considered**
In `google/cloud/firestore_v1/watch.py` - `push()` we could support async function as callback making use of `asyncio.run()`. I leave here the changes I made to make it work for myself. I added a single test to show the idea behind it.
[Potential Changes to propose in a PR](https://github.com/y3rbiadit0/python-firestore-async-on-snapshot-callback/tree/main)

**Comment by daniel-sanche** [comment]
Hey, thanks for the suggestion. Like I mentioned in your PR, we can't safely use `asyncio.run` to execute async code inside a sync function. To really solve this, we'd have to make a separate `AsyncWatch` class, like we do for the rest of the async functionality in the library. I'll add it to our task list, but this likely won't be on our roadmap in the near term

If you want to share some code for what you're trying to accomplish, I may be able to help find a workaround though.
