### ISSUE TITLE
When ServiceUnavailable is thrown, transaction silently loop forever

### ISSUE THREAD

**Issue by sjudd** [googleapis/python-firestore#850]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-firestore/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

I think these are not super relevant, but let me know if I'm wrong

  - OS type and version:
  - Python version: `python --version`
  - pip version: `pip --version`
  - `google-cloud-firestore` version: `pip show google-cloud-firestore`

#### Steps to reproduce

Run a transaction when upstream throws ServiceUnavailable

#### Code example

https://github.com/googleapis/python-firestore/blob/3a572b5d92b7bb20232b0b271a457fc4b6572f0e/google/cloud/firestore_v1/transaction.py#L347

#### Stack trace

NA?

It looks like the python client loops forever without logging anything if the client throws a ServiceUnavailable exception. It seems undesirable both to loop without a limit and also not to log anything (or have an option to log something) if a transient failure is hit.

In contrast in `__call__`, there's a loop with a reasonable maximum number of retries: https://github.com/googleapis/python-firestore/blob/3a572b5d92b7bb20232b0b271a457fc4b6572f0e/google/cloud/firestore_v1/transaction.py#L270.

I'd expect any retry loops to have a reasonable maximum time period or number of attempts. I'd also expect to be able to configure logging for transient failures so it's easier to understand when something isn't working.

**Comment by av1m** [comment]
Hello, for information I have a Cloud Run service in production which returns a lot of 504 errors.
By collecting the logs, I notice that a call to Firestore never returns a response (I have a log before the call and a log after the call).
I have the first but not the second log (which indicates that firestore is not returning a client)

My simplified code

```python
def get_conversation(self, conversation_id):
    logger.info("Get sms conversation %s", conversation_id)
    data = (
        self.collection.document("conversation")
        .get(field_paths=[conversation_id], timeout=10)
        .to_dict()
    )
    logger.info("Data: %s", data)
    return data
```

This code works but it sometimes happens that it runs in vain (and causes a 504 on Cloud Run)

So in my log i see 

```bash
… # Some logs
Get sms conversation 124214 # for example
```
And that's all; I don't have the log `Data: …`

_Btw, the timeout parameter doesn't work... And, if I set timeout=0, I have an infinite loop_

**Comment by garysmall** [comment]
Seeing the same issue with cloud run and concurrent requests.

**Comment by daniel-sanche** [comment]
For the first comment: the firestore library currently implements some custom retry logic, which has some issues we're aware of. We opened a milestone to track some work related to improving retires, which would address this concern: https://github.com/googleapis/python-firestore/milestone/4

**Comment by daniel-sanche** [comment]
For the other comments on 504: if you're encountering frequent 504 errors that are causing the library to block, that certainly seems serious. That seems unrelated to the initial bug though, because 504 errors are [GatewayTimeouts, not ServiceUnavaliable errors](https://github.com/googleapis/python-api-core/blob/fef936315f82a6b1db0bf23595e7bf71c7b503e4/google/api_core/exceptions.py#L428C22-L428C33). So it must have a different cause. Please open another bug with as much details as you can provide, and we can try to take a look

**Comment by daniel-sanche** [comment]
@gkevinzheng, can you take a look at getting https://github.com/googleapis/python-firestore/pull/948 merged this week while I'm out?
