### ISSUE TITLE
Typing for optional function parameters are incorrect

### ISSUE THREAD

**Issue by dcgudeman** [googleapis/python-firestore#854]
#### Environment details

  - OS type and version: MacOS
  - Python version: 3.11
  - pip version: 23.3.1
  - `google-cloud-firestore` version: 2.14.0

#### Steps to reproduce

  1. Use a function that has an optional parameter
  2. Observe type error

#### Code example

```python
async_client = AsyncClient()
async_col_ref = async_client.collection("users")
all_users = async_col_ref.stream()
```

#### Stack trace
```
Argument of type "None" cannot be assigned to parameter "transaction" of type "Transaction" in function "stream"
  "None" is incompatible with "Transaction"Pylance[reportArgumentType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportArgumentType)
```

**Comment by daniel-sanche** [comment]
parent issue: https://github.com/googleapis/python-firestore/issues/773

**Comment by daniel-sanche** [comment]
This should be fixed in https://github.com/googleapis/python-firestore/pull/984
