### ISSUE TITLE
Publish documentation as Dash docset

### ISSUE THREAD

**Issue by clarencecastillo** [googleapis/python-firestore#86]
Hi there, my apologies in advance if I'm asking this in the wrong place, but just want to check if it's permissible for me to contribute this project's documentation as a docset for [Dash](https://kapeli.com/dash)?

I have generated the sphinx docset using [doc2dash](https://doc2dash.readthedocs.io/en/stable/#) and have been using it offline using the app. I would think the Dash community will benefit from having an offline version of the documentation.

If granted permission, I will open a PR [here](https://github.com/Kapeli/Dash-User-Contributions) to contribute the docset to the public.

**Comment by crwilcox** [comment]
@clarencecastillo this isn't part of the Google Cloud Firestore Python library. Dash seems to indicate they can be contacted at support@kapeli.com.
