### ISSUE TITLE
Wrong return type in AsyncCollectionReference.list_documents

### ISSUE THREAD

**Issue by gblazq** [googleapis/python-firestore#918]
`AsyncCollectionReference.list_documents`'s return type is `AsyncGenerator[DocumentReference, None]`. However, since this is an AsyncCollection, it should be `AsyncGenerator[AsyncDocumentReference, None]`.

Similarly, in `base_collection._item_to_document_ref` the return type should be `DocumentReference | AsyncDocumentReference`, since it's using the collection's `document` method and that can return either type depending on the collection.

With the wrong types code editors and lint tools get confused :) 

#### Environment details

  - `google-cloud-firestore` version: 2.15.0

**Comment by daniel-sanche** [comment]
Thanks for the report. It's a known issue that the [typing for this library is currently broken](https://github.com/googleapis/python-firestore/issues/773). We will make sure to address this with the others

**Comment by daniel-sanche** [comment]
fixed in https://github.com/googleapis/python-firestore/pull/984
