### ISSUE TITLE
protobuf 5.26 support

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [googleapis/python-firestore#920]
google-cloud-firestore's current version is not compatible with protobuf 5.26's latest version.

Do you have any plans or ETA for making google-cloud-firestore compatible with the latest protobuf version?

**Comment by daniel-sanche** [comment]
This is something that is being addressed down the stack, and will roll out to all GCP libraries soon. Unfortunately I don't have a timeline on when to expect the change

**Comment by mering** [comment]
@daniel-sanche Thanks for the update and for working on it!
