### ISSUE TITLE
FirestoreAdminClient with emulator

### ISSUE THREAD

**Issue by pgridharan** [googleapis/python-firestore#941]
Hi,

I'm not sure if this is a bug or not a feature, but using the `FirestoreAdminClient` with the emulator does not work 😅 

#### Environment details

  - OS type and version: MacOS 14.5 with Docker 26.1.4, Compose v2.27.1-desktop.1, Docker Desktop 4.31.0
  - Python version: `Python 3.11.9`
  - pip version: `pip 24.0 from /usr/local/lib/python3.11/site-packages/pip (python 3.11)`
  - `google-cloud-firestore` version: `2.17.0`

#### Steps to reproduce

  1. Set `FIRESTORE_EMULATOR_HOST`
  2. Use `FirestoreAdminClient` instance

#### Code example

```.env
FIRESTORE_EMULATOR_HOST=0.0.0.0:8080
```

```python
load_dotenv()

print(os.getenv("FIRESTORE_EMULATOR_HOST"))                # Will print `0.0.0.0:8080`
admin_client = FirestoreAdminClient()
request = firestore_admin_v1.types.ListDatabasesRequest(
    parent=f"projects/test-project",
)
client.list_databases(request=request)                     # This should not matter since the emulator only supports one project AFAIK
```

#### Stack trace
```
google.api_core.exceptions.PermissionDenied: 403 Cloud Firestore API has not been used in project test-project before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/firestore.googleapis.com/overview?project=test-project then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

**Comment by tom-andersen** [comment]
Thank you for the question. I am going to find someone with more Python knowledge to answer.

**Comment by pgridharan** [comment]
Is there any update?

**Comment by daniel-sanche** [comment]
Unfortunately, the admin client is fully auto-generated, and does not support connecting to the emulator using just the `FIRESTORE_EMULATOR_HOST` env var. 

You can still connect to the emulator, but you need to do a but more work to configure the grpc channel yourself. It should look something like this:
```
from google.auth.credentials import AnonymousCredentials
from google.cloud.firestore_admin_v1.services.firestore_admin.transports.grpc import FirestoreAdminGrpcTransport
from google.cloud.firestore_admin_v1.services.firestore_admin import FirestoreAdminClient
import grpc

FIRESTORE_EMULATOR_HOST="0.0.0.0:8080"

credentials = AnonymousCredentials()
options = [("Authorization", f"Bearer owner")]
channel = grpc.insecure_channel(FIRESTORE_EMULATOR_HOST, options=options)
transport = FirestoreAdminGrpcTransport(host=FIRESTORE_EMULATOR_HOST, channel=channel, credentials=credentials)


admin_client = FirestoreAdminClient(transport=transport)
```
