### ISSUE TITLE
type issue: "StreamGenerator" is not iterable

### ISSUE THREAD

**Issue by shooit** [googleapis/python-firestore#947]
This issue was introduced with the changes in 2.17.0. It exists for each of the pyright version I tested at random.

It is only a type issue -- the code behaves as expected.

#### Environment details

  - OS type and version: MacOS
  - Python version: `python --version` 3.11.7
  - pip version: `pip --version` poetry
  - `google-cloud-firestore` version: `pip show google-cloud-firestore` 2.17.0
  - `pyright` version: 1.1.375

#### Steps to reproduce

  1. Setup environment as above
  2. Run pyright

#### Code example

```python
client = firestore_v1.Client()


def example():
    collection = client.collection("foo")
    docs = collection.stream()
    for doc in docs:
        print(doc)
```

<img width="687" alt="image" src="https://github.com/user-attachments/assets/f9689aff-ae25-4215-9545-83df17f159cc">

#### Error message
```
eample.py
  example.py:7:20 - error: "StreamGenerator" is not iterable
    "__next__" method not defined on type "DocumentSnapshot" (reportGeneralTypeIssues)
```

**Comment by daniel-sanche** [comment]
Thanks for letting us know. We're aware that the type annotations for this repo are [currently broken](https://github.com/googleapis/python-firestore/issues/773). But @Linchin is [working on some changes](https://github.com/googleapis/python-firestore/pull/938) related to the StreamGenerator, so maybe this can be addressed there

**Comment by Linchin** [comment]
The type annotation changes in #938 should be able to resolve this error, but I don't think this single PR will clean up all existing type annotation errors.

**Comment by jekozyra** [comment]
fyi, this is broken for `AsyncStreamGenerator` as well.

**Comment by Linchin** [comment]
It can be fixed by adding type annotation to the init function of StreamGenerator [here](https://github.com/googleapis/python-firestore/blob/ea64f23a68d7610ce7ed3369c723e2cbffd2c56d/google/cloud/firestore_v1/stream_generator.py#L24). I'm still not 100% sure, but it feels like pyright is trying to infer the parameter type, but somehow wasn't correct (probably due to other type annotation errors.)
