### ISSUE TITLE
Run Cross Language tests for v2

### ISSUE THREAD

**Issue by crwilcox** [googleapis/python-firestore#95]
tests/unit/v1/test_cross_language.py → tests/unit/v1/_test_cross_language.py 

remove the leading `_` and begin testing with these again. Disabled as the protos for this need to be generated with protoplus to run correctly. (see makefile)

**Comment by HemangChothani** [comment]
@crwilcox  I have generated `test.proto` file as per mentioned in `makefile`, so should i open a PR `https://github.com/googleapis/googleapis`  here with new generated test.proto file?

**Comment by crwilcox** [comment]
@HemangChothani you modified the makefile to generate using protoplus?

**Comment by HemangChothani** [comment]
@crwilcox  No, i didn't make any changes in makefile, i had follow the steps and generate `test_pb2.py` file, i don't know what to make changes in makefile related to `protoplus`, i have tried to find any related documentation, but not succeed.
